/* Английские переводы для «Амур Атласа». Ключ — русский оригинал (как в разметке),
   значение — английский. Движок i18n в index.html подменяет текст по совпадению ключа.
   Нет ключа — на сайте остаётся русский. Правьте свободно: сборки нет, файл статичный. */
window.EN = {
  '@title': `Blagoveshchensk: what to see, trips and a visit to Heihe — Amur Atlas guide`,
  '@desc': `A local's guide to Blagoveshchensk: 23 map points, a trip planner with a budget, how to cross into China's Heihe visa-free, the cable car, seasons and prices. Verified facts, July 2026.`,

  /* --- ДИНАМИКА: панель маршрута, конструктор, события (служебное) --- */
  'Ваш маршрут на карте': `Your route on the map`,
  'Убрать с карты ✕': `Clear from map ✕`,
  'Выберите день — точки этого дня появятся на карте линией маршрута.': `Pick a day — its points appear on the map as a route line.`,
  'подробнее →': `details →`,
  'В этой категории пока нет событий. Попробуйте «Все».': `No events in this category yet. Try "All".`,
  'фестиваль': `festival`, 'выставка': `exhibition`, 'гастро': `food`,
  'природа': `nature`, 'спектакль': `theatre`, 'ярмарка': `market`,
  /* конструктор маршрута */
  'выберите ≥1': `pick ≥1`,
  'итого': `total`,
  'Дневной бюджет (еда, транспорт)': `Daily budget (food, transport)`,
  'Активности и экскурсии': `Activities and tours`,
  'Дорога до города (ориентир)': `Getting to the city (estimate)`,
  'На человека': `Per person`,
  'В день (на всех)': `Per day (all)`,
  'Активностей': `Activities`,
  'Ночей': `Nights`,
  'сезон:': `season:`,
  'бюджет': `budget`,
  'День': `Day`,
  'Показать маршрут на карте →': `Show the route on the map →`,
  'Приезд и знакомство с городом': `Arrival and getting to know the city`,
  'Отдых и отъезд': `Rest and departure`,
  'День в Приамурье': `A day in the Amur region`,
  'бесплатно': `free`,
  'Забрать маршрут с собой': `Take the route with you`,
  'Скачать PDF': `Download PDF`,
  'Поделиться ссылкой': `Share a link`,
  'Дата приезда:': `Arrival date:`,
  'В календарь (.ics)': `To calendar (.ics)`,
  /* темы дней (DAYTHEME) */
  'Амур и набережная': `The Amur and the embankment`,
  'Природа Приамурья': `Nature of the Amur region`,
  'История и купцы': `History and merchants`,
  'Активный день': `An active day`,
  'Гастрономический день': `A food day`,
  'Отдых на природе': `Rest in nature`,
  'Городской день': `A city day`,
  'Семейный день': `A family day`,
  /* теги активностей (TAGL) */
  'река': `river`, 'еда': `food`, 'история': `history`, 'актив': `active`,
  'семья': `family`, 'отдых': `leisure`, 'город': `city`,
  /* --- ТОЧКИ КАРТЫ (POINTS) --- */
  'Набережная Амура': `The Amur Embankment`,
  'Километры прогулочного берега лицом к китайскому Хэйхэ. Новый участок «Серебряная миля» (~2,5 км) с 500-метровым пляжем, велодорожки, воркаут-зоны, ролледром и стритбол, маршрут скандинавской ходьбы, детские площадки, прокаты. Ориентиры — башня старого маяка у горпарка, ротонда и памятники, включая пса Дружка.': `Kilometres of promenade facing Chinese Heihe. The new "Silver Mile" stretch (~2.5 km) has a 500-metre beach, bike lanes, workout zones, a roller rink and streetball, a Nordic-walking trail, playgrounds and rentals. Landmarks: the old lighthouse tower by the city park, the rotunda and monuments, including Druzhok the dog.`,
  'Триумфальная арка': `The Triumphal Arch`,
  '20-метровая арка с двуглавыми орлами на набережной. Восстановлена в 2005 году по фото оригинала 1891 года — к визиту цесаревича Николая. Визитная карточка Благовещенска.': `A 20-metre arch with double-headed eagles on the embankment. Rebuilt in 2005 from photos of the 1891 original, raised for Tsarevich Nicholas's visit. Blagoveshchensk's signature sight.`,
  'Кафедральный собор Благовещения': `The Annunciation Cathedral`,
  'Главный храм города, семь золочёных куполов, освящён в 2003 году. Хранит чтимую Албазинскую икону Божией Матери «Слово плоть бысть».': `The city's main church, seven gilded domes, consecrated in 2003. It holds the venerated Albazin Icon of the Mother of God.`,
  'Краеведческий музей им. Новикова-Даурского': `Novikov-Daursky Regional Museum`,
  'Один из старейших на Дальнем Востоке (осн. 1891). ~166 тыс. единиц хранения: от палеонтологии Приамурья до казачества и приграничья.': `One of the oldest in the Far East (founded 1891). ~166,000 items: from Amur-region palaeontology to the Cossacks and the borderland.`,
  'Канатная дорога Благовещенск–Хэйхэ': `Blagoveshchensk–Heihe Cable Car`,
  'Первая в мире трансграничная канатка через госграницу. Натяжка каната через Амур завершена в июле 2026, запуск намечен на конец года. 2 кабины по 110 чел., 6–8 минут в пути.': `The world's first cross-border cable car over a state frontier. The cable across the Amur was strung in July 2026; opening is set for year's end. 2 cabins of 110 people, 6–8 minutes each way.`,
  'Трансграничный мост через Амур': `The cross-border bridge over the Amur`,
  'Первый автомост Россия–Китай (Кани-Курган, ~13 км от центра), открыт для грузов в 2022 году. С 2026-го пущены пассажирские автобусы Благовещенск–Хэйхэ.': `The first Russia–China road bridge (Kani-Kurgan, ~13 km from the centre), opened for freight in 2022. Passenger buses Blagoveshchensk–Heihe started in 2026.`,
  'Площадь Ленина и «Трибуна Холл»': `Lenin Square and "Tribuna Hall"`,
  'Сердце города после реконструкции: крупнейший в Евразии пешеходный светомузыкальный фонтан (~3 000 м², сезон с 1 мая, вечером — водно-световое шоу), динопарк с 10-метровым амурозавром, интерактивный музей динозавров и космопарк «Амурский» с VR-полётами, 75-метровый флагшток.': `The city's heart after its makeover: Eurasia's largest walk-through light-and-music fountain (~3,000 m², season from 1 May, an evening water-and-light show), a dino park with a 10-metre amurosaurus, an interactive dinosaur museum and the "Amursky" space park with VR flights, plus a 75-metre flagpole.`,
  'Общественно-культурный центр (ОКЦ)': `Public and Cultural Centre (OKTs)`,
  'Крупнейшая концертно-выставочная площадка города. «Дом» многих событий кинофестиваля «Амурская осень».': `The city's largest concert and exhibition venue. Home to many events of the "Amur Autumn" film festival.`,
  'Первомайский парк': `Pervomaisky Park`,
  'Старейший парк города: тенистые аллеи, аттракционы, детские площадки. Приятно погулять.': `The city's oldest park: shady lanes, rides, playgrounds. A pleasant stroll.`,
  'Памятник Муравьёву-Амурскому': `Monument to Muravyov-Amursky`,
  'Бронзовая фигура основателя города и «собирателя» Приамурья на набережной. Смотрит на Амур и Китай.': `A bronze figure of the city's founder and "gatherer" of the Amur region, on the embankment. He looks out at the Amur and China.`,
  'Амурский областной театр драмы': `Amur Regional Drama Theatre`,
  'Один из старейших театров Дальнего Востока (осн. 1883). Главная сцена театральной программы «Амурской осени».': `One of the oldest theatres in the Far East (founded 1883). The main stage of the "Amur Autumn" theatre programme.`,
  'Пожарная каланча': `The fire-watch tower`,
  'Кирпичная башня 1909–1914 годов в духе замковой архитектуры. Доминанта исторической Амурской улицы, символ купеческого Благовещенска.': `A brick tower of 1909–1914 in a castle-like style. The landmark of historic Amurskaya Street and a symbol of merchant Blagoveshchensk.`,
  'Парк Дружбы': `Friendship Park`,
  'Зелёная зона в китайском стиле с искусственным водопадом и скейт-парком — знак приграничного соседства.': `A Chinese-style green area with an artificial waterfall and a skate park — a mark of the border neighbourhood.`,
  'Благовещенское «кладбище динозавров»': `The Blagoveshchensk "dinosaur graveyard"`,
  'Городское захоронение позднемеловых ящеров (амурозавры и другие гадрозавры) прямо в черте города, район ул. Нагорной. Одно из богатейших в России; раскопки ведёт Амурский научный центр.': `A unique urban bonebed of Late Cretaceous reptiles (amurosaurs and other hadrosaurs) right within the city, near Nagornaya Street. One of the richest in Russia; excavated by the Amur Scientific Centre.`,
  'Музей палеонтологии АмурНЦ ДВО РАН': `Palaeontology Museum, Amur Scientific Centre`,
  'Диорамы и подлинные кости динозавров и мамонтов Приамурья. Научная база городского «кладбища динозавров».': `Dioramas and genuine bones of the Amur region's dinosaurs and mammoths. The research base of the city's "dinosaur graveyard".`,
  'Турбаза и санатории Мухинка': `Mukhinka resorts and lodges`,
  'Популярная зона отдыха на берегу Зеи, ~35 км севернее города. Сосновый бор, санатории, базы. Летний отдых горожан.': `A popular getaway on the Zeya, ~35 km north of the city. Pine forest, sanatoriums, lodges. Locals' summer retreat.`,
  'Космодром Восточный / Циолковский': `Vostochny Cosmodrome / Tsiolkovsky`,
  'Новая космическая эпоха Приамурья, ~180 км от Благовещенска (3–4 ч). Экскурсии по предварительной заявке, смотровые площадки при пусках.': `The Amur region's new space era, ~180 km from Blagoveshchensk (3–4 h). Tours by prior booking, viewing areas during launches.`,
  'Албазинский острог': `Albazin Fort`,
  'Первое русское поселение на Амуре (1651) и место героической обороны 1685–1686 годов. Ныне музейно-культурный центр и реконструкция острога (Сковородинский р-н).': `The first Russian settlement on the Amur (1651) and the site of the heroic defence of 1685–1686. Today a museum-cultural centre with a reconstructed fort (Skovorodino district).`,
  'Озеро лотосов у Ивановки': `Lotus lake near Ivanovka`,
  'Заросли краснокнижного лотоса Комарова, цветут в июле–августе. ~40 км от города, популярная летняя фотолокация.': `Thickets of the protected Komarov lotus, blooming in July–August. ~40 km from the city, a popular summer photo spot.`,
  'Памятник псу Дружку': `Monument to Druzhok the dog`,
  'Бронзовый пёс на набережной — трогательный символ наводнения 2013 года: во время большой воды он несколько дней ждал хозяев на крыльце затопленного дома. Теперь, по словам горожан, «охраняет весь город».': `A bronze dog on the embankment — a touching symbol of the 2013 flood: during the high water he waited days for his owners on the porch of a flooded house. Now, locals say, he "guards the whole city".`,
  'Музей истории Амурского казачества': `Museum of Amur Cossack History`,
  'Экспозиция о роли казачества в освоении Приамурья и охране границы — в селе Черняево (Магдагачинский р-н, ~250 км от города). Быт, оружие, форма переселенцев.': `An exhibition on the Cossacks' role in settling the Amur region and guarding the border — in the village of Chernyayevo (Magdagachi district, ~250 km from the city). Everyday life, weapons, settlers' uniforms.`,
  'Музей-калачная в Универмаге Платоновых': `Kalach Museum in the Platonov Department Store`,
  'Музей русского калача в историческом универмаге братьев Платоновых (1900–1901): выпечка по старинной технологии, экскурсии с дегустацией — по записи. Амурская, 199, угол 50 лет Октября.': `A museum of the Russian kalach loaf in the historic Platonov Brothers department store (1900–1901): baking by old methods, tours with tasting — by appointment. 199 Amurskaya St, corner of 50 Let Oktyabrya.`,
  'Кундурское местонахождение динозавров': `The Kundur dinosaur site`,
  'Второе знаменитое «кладбище динозавров» области (Архаринский р-н, ~350 км). Здесь найден олоротитан — «дальневосточный утконосый ящер».': `The region's second famous "dinosaur graveyard" (Arkharinsky district, ~350 km). Olorotitan — the "Far Eastern duck-billed dinosaur" — was found here.`,

  /* заметки по сезону в конструкторе */
  'Зима — замёрзший Амур, каток и огни Хэйхэ через реку. Дальние поездки (космодром, Албазино) сложнее из-за морозов.': `Winter — a frozen Amur, a rink and the lights of Heihe across the river. Long trips (the cosmodrome, Albazino) are harder in the cold.`,
  'Весна — ледоход на Амуре, низкий сезон, минимум туристов. Город и музеи доступны полностью.': `Spring — the ice drift on the Amur, low season, few tourists. The city and museums are fully open.`,
  'Лето — пик: набережная, лотосы, отдых на Зее, поездки в Хэйхэ и на Восточный. Дороже и жарче.': `Summer — peak: the embankment, lotuses, rest on the Zeya, trips to Heihe and Vostochny. Pricier and hotter.`,
  'Осень — золотой сезон: кинофестиваль «Амурская осень», тёплое бабье лето, ярмарки урожая.': `Autumn — the golden season: the "Amur Autumn" film festival, warm Indian summer, harvest fairs.`,

  /* --- АКТИВНОСТИ КОНСТРУКТОРА (ACT) --- */
  'Прогулка по набережной Амура': `A walk along the Amur embankment`,
  'Километры берега лицом к Хэйхэ: «Серебряная миля», пляж, велодорожки, спортплощадки, старый маяк. Городская акклиматизация в первый день.': `Kilometres of riverfront facing Heihe: the "Silver Mile", a beach, bike lanes, sports grounds, the old lighthouse. City acclimatisation for the first day.`,
  'Триумфальная арка и памятник Муравьёву': `The Triumphal Arch and the Muravyov monument`,
  'Визитная карточка города на набережной и бронзовый основатель Приамурья.': `The city's signature sight on the embankment and the bronze founder of the Amur region.`,
  'Семь золочёных куполов, Албазинская икона. Главный храм города.': `Seven gilded domes, the Albazin icon. The city's main church.`,
  'Один из старейших на Дальнем Востоке: палеонтология, казачество, приграничье.': `One of the oldest in the Far East: palaeontology, the Cossacks, the borderland.`,
  'Канатная дорога в Хэйхэ': `Cable car to Heihe`,
  'Первая в мире трансграничная канатка через Амур в Китай (запуск конца 2026). Кабина — 6–8 минут над границей.': `The world's first cross-border cable car over the Amur into China (opening late 2026). A cabin ride is 6–8 minutes over the border.`,
  'Поездка в китайский Хэйхэ': `A trip to Chinese Heihe`,
  'Сосед за рекой: рынки, кухня, массаж. Нужен загранпаспорт; автобус по мосту или паром.': `The neighbour across the river: markets, food, massage. A passport is needed; bus over the bridge or a ferry.`,
  'Музей палеонтологии + «кладбище динозавров»': `Palaeontology museum + the "dinosaur graveyard"`,
  'Кости позднемеловых ящеров прямо из городского захоронения. Восторг для детей и взрослых.': `Late Cretaceous reptile bones straight from the city bonebed. A thrill for kids and adults.`,
  'Купеческий центр пешком': `The merchant centre on foot`,
  'Пожарная каланча, каменные особняки, Амурская улица — прогулка по «Амурскому Чикаго».': `The fire tower, stone mansions, Amurskaya Street — a walk through the "Amur Chicago".`,
  'Отдых на Зее (Мухинка)': `Rest on the Zeya (Mukhinka)`,
  'Сосновый бор и берег Зеи в ~35 км: базы, санатории, купание летом.': `Pine forest and the Zeya bank ~35 km away: lodges, sanatoriums, swimming in summer.`,
  'Краснокнижный лотос Комарова, цветёт в июле–августе. ~40 км, лучшая летняя фотолокация.': `The protected Komarov lotus, blooming in July–August. ~40 km away, the best summer photo spot.`,
  'Рыбалка на озёрах Приамурья': `Fishing on the Amur region's lakes`,
  'Тихие озёра и старицы в окрестностях города — рыбалка и отдых на природе.': `Quiet lakes and oxbows around the city — fishing and rest in nature.`,
  'Гастроужин: амурская рыба и уха': `Food dinner: Amur fish and fish soup`,
  'Сазан, верхогляд, наваристая уха. Речная классика Приамурья.': `Carp, skygazer, a rich fish soup. The river classics of the Amur region.`,
  'Дунбэйская кухня Хэйхэ в городе': `Heihe's Dongbei cuisine in town`,
  'Го-бао-жоу, баклажаны по-сычуаньски, лапша. Сотни китайских кафе, недорого.': `Guo bao rou, Sichuan-style aubergine, noodles. Hundreds of Chinese cafés, cheap.`,
  'Рынок: соя, мёд, дикоросы': `The market: soy, honey, wild harvest`,
  'Тофу и соевое молоко, таёжный мёд, лимонник и папоротник. Сувениры в дорогу.': `Tofu and soy milk, taiga honey, schisandra and fern. Souvenirs for the road.`,
  'Экскурсия на космодром Восточный': `Tour of the Vostochny Cosmodrome`,
  '~180 км от города (3–4 ч). Стартовый стол и наукоград Циолковский по предварительной заявке.': `~180 km from the city (3–4 h). The launch pad and the science town of Tsiolkovsky by prior booking.`,
  'Албазинский острог': `Albazin Fort`,
  'Первый русский форпост на Амуре (1651) и место обороны 1685–1686. Реконструкция острога, музей.': `The first Russian outpost on the Amur (1651) and the site of the 1685–1686 defence. A reconstructed fort and a museum.`,
  'Мост через Амур и Кани-Курган': `The Amur bridge and Kani-Kurgan`,
  'Первый автомост Россия–Китай. Смотровая точка на границу двух стран.': `The first Russia–China road bridge. A viewpoint over the border of two countries.`,
  'Музей амурского казачества': `Museum of the Amur Cossacks`,
  'Быт, оружие и форма переселенцев, охранявших Приамурье.': `Everyday life, weapons and uniforms of the settlers who guarded the Amur region.`,
  'Первомайский парк с детьми': `Pervomaisky Park with kids`,
  'Старейший парк города: аллеи, аттракционы, ручные белки.': `The city's oldest park: lanes, rides, tame squirrels.`,
  'Спектакль в театре драмы': `A play at the drama theatre`,
  'Один из старейших театров ДВ (1883). Особенно ярко — в дни «Амурской осени».': `One of the oldest theatres in the Far East (1883). Especially vivid during "Amur Autumn".`,
  'Кинофестиваль «Амурская осень»': `The "Amur Autumn" film festival`,
  'Главное культурное событие: кино, театр, звёзды на набережной. Ежегодно в сентябре.': `The main cultural event: film, theatre, stars on the embankment. Every September.`,
  'Зимний Амур: лёд и виды на Хэйхэ': `Winter Amur: ice and views of Heihe`,
  'Замёрзшая река, каток, огни китайского берега. Зимняя открытка Благовещенска.': `A frozen river, a rink, the lights of the Chinese bank. Blagoveshchensk's winter postcard.`,

  /* --- СОБЫТИЯ (FALLBACK_EVENTS) --- */
  'Цветение лотосов Комарова': `Bloom of the Komarov lotuses`,
  'Краснокнижный лотос зацветает на озёрах у села Ивановка. Массовые фотопоездки — лучшее время июль–август.': `The protected lotus blooms on the lakes near Ivanovka. Popular photo trips — best time July–August.`,
  'Ярмарка «Дальневосточный урожай»': `"Far Eastern Harvest" fair`,
  'Соя и тофу, таёжный мёд, дикоросы, амурская рыба. Фермеры Приамурья и гостинцы в дорогу.': `Soy and tofu, taiga honey, wild harvest, Amur fish. Amur-region farmers and treats for the road.`,
  'Российско-Китайская ярмарка культуры и искусства': `Russia–China Fair of Culture and Art`,
  'Ежегодный трансграничный фестиваль Благовещенск–Хэйхэ: концерты, ремёсла и кухня двух стран на набережной.': `An annual cross-border festival Blagoveshchensk–Heihe: concerts, crafts and the food of two countries on the embankment.`,
  'Гастрофестиваль амурской и китайской кухни': `Food festival of Amur and Chinese cuisine`,
  'Речная рыба, уха, дунбэйские блюда, соевые специалитеты. Дегустации и фудкорт под открытым небом.': `River fish, fish soup, Dongbei dishes, soy specialties. Tastings and an open-air food court.`,
  'XXIV кинофестиваль «Амурская осень»': `24th "Amur Autumn" film festival`,
  'Главное культурное событие города: российские кинопремьеры и театр, звёзды на набережной. Ежегодно — десятки тысяч гостей.': `The city's main cultural event: Russian film premieres and theatre, stars on the embankment. Tens of thousands of guests every year.`,
  'Премьера в Амурском театре драмы': `Premiere at the Amur Drama Theatre`,
  'Новый сезон одного из старейших театров Дальнего Востока (осн. 1883). Вечерний показ.': `A new season at one of the Far East's oldest theatres (founded 1883). Evening performance.`,
  'Запуск сезона фонтанов на площади Ленина': `Fountain season opens on Lenin Square`,
  'Крупнейший в Евразии пешеходный светомузыкальный фонтан открывает сезон: днём — водно-музыкальное шоу, вечером — светомузыка. Работает до осени.': `Eurasia's largest walk-through light-and-music fountain opens the season: a water-and-music show by day, light-and-music by night. Runs until autumn.`,
  'Ледоход на Амуре': `Ice drift on the Amur`,
  'Амур вскрывается на глазах у всего города — главное зрелище весны. Точные даты зависят от погоды, обычно конец апреля.': `The Amur breaks up before the whole city — the main spring spectacle. Exact dates depend on the weather, usually late April.`,
  'Ледовый городок на площади Ленина': `Ice town on Lenin Square`,
  'Новогодний городок с горками и подсветкой — зимняя классика Благовещенска у главной ёлки города.': `A New Year town with slides and lights — a Blagoveshchensk winter classic by the city's main tree.`,
  'Выставка «Приамурье: от динозавров до космоса»': `Exhibition "The Amur region: from dinosaurs to space"`,
  'Палеонтология и космодром Восточный в одном зале краеведческого музея. Кости ящеров и модели ракет.': `Palaeontology and the Vostochny Cosmodrome in one hall of the regional museum. Reptile bones and rocket models.`,
  /* локации событий */
  'Площадь Ленина': `Lenin Square`,
  'Окрестности с. Ивановка · ~40 км': `Near Ivanovka village · ~40 km`,
  'ОКЦ / Театр драмы': `OKTs / Drama Theatre`,
  'Театр драмы · ул. Ленина 146': `Drama Theatre · 146 Lenina St`,
  'Краеведческий музей · ул. Ленина 165': `Regional Museum · 165 Lenina St`,

  /* загрузчик + шапка */
  'Благовещенск': `Blagoveshchensk`,
  'Амур Атлас': `Amur Atlas`,
  'Зачем ехать': `Why go`,
  'Карта': `Map`,
  'События': `Events`,
  'Как доехать': `Getting there`,
  'Хэйхэ': `Heihe`,
  'Канатка': `Cable car`,
  'Маршрут': `Planner`,
  'История': `History`,
  'Любопытное': `Curious`,
  'Собрать маршрут': `Plan a trip`,

  /* hero */
  'Авторский гид · ИИщенко LAB': `An indie guide · Iishchenko LAB`,
  'Благовещенск:<br>город на Амуре,<br>лицом к <span class="g">Китаю</span>': `Blagoveshchensk:<br>a city on the Amur,<br>facing <span class="g">China</span>`,
  'Благовещенск — 750 метров воды до китайского Хэйхэ, купеческий «Амурский Чикаго», кухня двух стран, космодром Восточный и городское кладбище динозавров. Соберём маршрут под ваши интересы, сезон и бюджет.': `Blagoveshchensk sits just 750 metres of water from China's Heihe: a merchant-era "Amur Chicago", the cuisine of two countries, the Vostochny Cosmodrome, and a dinosaur graveyard right inside town. Let's build a trip around your interests, season and budget.`,
  'Собрать маршрут <span>→</span>': `Plan a trip <span>→</span>`,
  'Открыть карту': `Open the map`,
  '<b>23</b> точки на карте': `<b>23</b> points on the map`,
  '<b>4</b> эпохи истории': `<b>4</b> eras of history`,
  '<b>2</b> страны на тарелке': `<b>2</b> countries on a plate`,
  'RU ↔ CN<span>Амур · граница</span>': `RU ↔ CN<span>Amur · border</span>`,
  '<span class="dot"></span>Арка, Амур — и Хэйхэ за рекой': `<span class="dot"></span>The arch, the Amur — and Heihe beyond`,
  'воды до китайского Хэйхэ': `of water to China's Heihe`,
  'год основания города': `the year the city was founded`,
  'до космодрома Восточный': `to the Vostochny Cosmodrome`,
  'лет динозаврам под городом': `years — the dinosaurs beneath the city`,

  /* eyebrows секций */
  '01 — зачем ехать': `01 — why go`,
  '02 — интерактивная карта': `02 — interactive map`,
  '03 — что сейчас': `03 — what's on`,
  '04 — практика поездки': `04 — trip basics`,
  '05 — две страны за один день': `05 — two countries in a day`,
  '06 — скоро': `06 — coming soon`,
  '07 — конструктор маршрута': `07 — trip planner`,
  '08 — история': `08 — history`,
  '09 — гастрономия': `09 — food`,
  '10 — любопытное': `10 — curious facts`,
  '11 — вопросы': `11 — questions`,
  '12 — прогулка': `12 — a walk`,
  '13 — галерея': `13 — gallery`,

  /* заголовки и лиды секций */
  'Четыре разных Благовещенска<br>в одной <em>поездке</em>': `Four different Blagoveshchensks<br>in a single <em>trip</em>`,
  'За несколько дней — пройти по набережной лицом к китайскому мегаполису, застать купеческий «Амурский Чикаго», потрогать кости динозавров и увидеть, откуда стартуют ракеты.': `In a few days you can walk the embankment facing a Chinese metropolis, catch the merchant-era "Amur Chicago", touch dinosaur bones and see where the rockets launch.`,
  'Двадцать три <em>точки силы</em>': `Twenty-three <em>points of interest</em>`,
  'Кликайте на маркеры — описание и фото. Фильтруйте по категориям, чтобы спланировать день.': `Click a marker for a description and photo. Filter by category to plan your day.`,
  'События <em>прямо сейчас</em>': `Events <em>on right now</em>`,
  'Как добраться, когда ехать<br>и <em>сколько это стоит</em>': `How to get here, when to go<br>and <em>what it costs</em>`,
  'Благовещенск — 5 595 км от Москвы и шесть часовых поясов на восток. Разбираемся, чем сюда добираются, какой сезон под какие впечатления и на какие суммы ориентироваться.': `Blagoveshchensk is 5,595 km east of Moscow and six time zones away. Here's how people get here, which season fits which mood, and the sums to plan around.`,
  'Утром Россия,<br>днём <em>Китай</em>': `Russia in the morning,<br><em>China</em> by noon`,
  'Хэйхэ виден с набережной — 750 метров воды. Визы не нужно, хватает загранпаспорта: доехать до соседней страны отсюда проще и дешевле, чем до соседнего областного центра. Считаем, во что обойдётся.': `Heihe is right there from the embankment — 750 metres of water. No visa needed, just a passport: reaching the neighbouring country is easier and cheaper than the next region over. Let's price it out.`,
  'Первая в мире канатка<br><em>между двумя странами</em>': `The world's first cable car<br><em>between two countries</em>`,
  'Через Амур тянут канатную дорогу из России в Китай — такого нет больше нигде. Вместо парома и автобуса с формальностями — кабина и несколько минут над пограничной рекой. Стройку начали в 2019 году, сейчас она на финишной прямой.': `A cable car is being strung across the Amur from Russia to China — the only one of its kind anywhere. Instead of a ferry or a bus with formalities, a cabin and a few minutes above the border river. Construction began in 2019 and is now in its final stretch.`,
  'Соберём <em>персональный</em> маршрут': `Let's build your <em>personal</em> route`,
  'Алгоритм учитывает состав группы, сезон, интересы и бюджет — раскладывает активности по дням и прозрачно считает стоимость.': `The planner factors in your group, season, interests and budget — it spreads activities across days and prices everything transparently.`,
  'Четыре эпохи <em>на берегу Амура</em>': `Four eras <em>on the bank of the Amur</em>`,
  'Албазинский острог XVII века, рождение города при Муравьёве-Амурском, купеческий «Амурский Чикаго» и приграничный город XX–XXI веков — от погранзоны до моста и канатки в Китай.': `The 17th-century Albazin fort, the city's birth under Muravyov-Amursky, the merchant-era "Amur Chicago", and the 20th–21st-century border city — from a closed frontier to a bridge and a cable car into China.`,
  'Кухня <em>двух стран</em> на одном столе': `The cuisine of <em>two countries</em> on one table`,
  'Дунбэйская кухня соседнего Хэйхэ давно стала городской повседневностью, а рядом — амурская речная рыба, соя «соевой столицы» России, таёжные дикоросы и наследие казачества.': `The Dongbei cooking of neighbouring Heihe has long been everyday fare here — alongside Amur river fish, soy from Russia's "soy capital", wild taiga harvests and a Cossack heritage.`,
  'Неожиданный <em>Благовещенск</em>': `The <em>Blagoveshchensk</em> you don't expect`,
  'Факты, курьёзы и городские байки, которые превращают поездку в историю — из впечатлений тех, кто уже съездил на границу двух миров.': `Facts, oddities and city lore that turn a trip into a story — from those who've already been to this border between two worlds.`,
  'Что спрашивают <em>перед поездкой</em>': `What people ask <em>before the trip</em>`,
  'Короткие ответы на то, что обычно выясняют в первую очередь. Подробности — в блоках выше.': `Quick answers to the things people check first. Details are in the sections above.`,
  'Пройдёмся по <em>набережной</em>': `Let's walk the <em>embankment</em>`,
  'Пять шагов вдоль Амура — от Триумфальной арки до поющего фонтана. Листайте: карта идёт следом за вами.': `Five stops along the Amur — from the Triumphal Arch to the singing fountain. Scroll, and the map follows you.`,
  'Благовещенск <em>в кадре</em>': `Blagoveshchensk <em>in frame</em>`,
  'Набережная лицом к Китаю, Триумфальная арка, мост через Амур, космос и динозавры.': `The embankment facing China, the Triumphal Arch, the bridge across the Amur, space and dinosaurs.`,

  /* футер */
  'Готовы <em>увидеть</em> Благовещенск?': `Ready to <em>see</em> Blagoveshchensk?`,
  'К конструктору маршрута →': `To the trip planner →`,
  'Сайт создан жителем Благовещенска по собственной инициативе': `Made by a Blagoveshchensk local, on personal initiative`,
  'v2.0 · Амур Атлас · Благовещенск': `v2.0 · Amur Atlas · Blagoveshchensk`,

  /* единицы у счётчиков */
  'м': `m`, 'км': `km`, 'млн': `M`,

  /* WHY — bento */
  'Амур и граница': `The Amur and the border`,
  'Набережная, Триумфальная арка, памятник Муравьёву-Амурскому, первый автомост Россия–Китай и первая в мире трансграничная канатка в Хэйхэ.': `The embankment, the Triumphal Arch, the Muravyov-Amursky monument, the first Russia–China road bridge and the world's first cross-border cable car to Heihe.`,
  'воды до Китая — города стоят «глаза в глаза»': `of water to China — the cities stand eye to eye`,
  'Купеческий след': `A merchant past`,
  '«Амурский Чикаго»: золотая лихорадка, каменные особняки, пожарная каланча и три века казачества.': `The "Amur Chicago": a gold rush, stone mansions, a fire-watch tower and three centuries of Cossacks.`,
  'Кухня двух стран': `Cuisine of two countries`,
  'Дунбэйская кухня Хэйхэ, амурская речная рыба и уха, соя и тофу «соевой столицы», таёжные дикоросы и мёд, папоротник по-корейски.': `Heihe's Dongbei cooking, Amur river fish and fish soup, soy and tofu from the "soy capital", wild taiga harvests and honey, Korean-style fern.`,
  'Космос и динозавры': `Space and dinosaurs`,
  'Городское «кладбище динозавров» и старты ракет в 180 км — прошлое и будущее Приамурья рядом.': `A city dinosaur graveyard and rocket launches 180 km away — the Amur region's past and future side by side.`,

  /* карта — фильтры и панель */
  'Все 23': `All 23`,
  '<span class="dot" style="background:var(--c-nat)"></span>Природа': `<span class="dot" style="background:var(--c-nat)"></span>Nature`,
  '<span class="dot" style="background:var(--c-sea)"></span>Река': `<span class="dot" style="background:var(--c-sea)"></span>River`,
  '<span class="dot" style="background:var(--c-his)"></span>История': `<span class="dot" style="background:var(--c-his)"></span>History`,
  '<span class="dot" style="background:var(--c-gas)"></span>Гастро': `<span class="dot" style="background:var(--c-gas)"></span>Food`,
  '<span class="dot" style="background:var(--c-spa)"></span>Отдых': `<span class="dot" style="background:var(--c-spa)"></span>Leisure`,
  '<span class="dot" style="background:var(--c-city)"></span>Город': `<span class="dot" style="background:var(--c-city)"></span>City`,
  'Точки по категориям': `Points by category`,
  'Из чего складываются 23 места': `What the 23 spots break down into`,

  /* события — вкладки */
  'афиша сезона': `this season's lineup`,
  'Все': `All`, 'Фестивали': `Festivals`, 'Выставки': `Exhibitions`, 'Гастро': `Food`,
  'Природа': `Nature`, 'Спектакли': `Theatre`, 'Ярмарки': `Markets`,

  /* практика поездки — как добраться */
  'Как добраться': `Getting there`,
  'Три дороги в город на Амуре': `Three roads into the city on the Amur`,
  'Самолётом': `By plane`,
  'Прямые рейсы из Москвы — 5 595 км, от 7 ч 25 мин. Аэропорт Игнатьево (BQS) в 15 км от центра: городской автобус №8, пригородные 503 и 510 до автовокзала, такси — 20–30 минут. Разница с Москвой +6 часов, к перелёту добавьте день на акклиматизацию.': `Direct flights from Moscow — 5,595 km, from 7 h 25 min. Ignatyevo airport (BQS) is 15 km from the centre: city bus No. 8, suburban buses 503 and 510 to the coach station, a taxi 20–30 minutes. Moscow is 6 hours behind, so add a day to adjust after the flight.`,
  'Поездом': `By train`,
  'Транссиб проходит мимо города: ближайший узел — Белогорск, около 110 км. Оттуда до Благовещенска автобус или пригородный поезд, 2–2,5 часа. Вариант для тех, кто едет за дорогой, а не за скоростью.': `The Trans-Siberian bypasses the city: the nearest hub is Belogorsk, about 110 km away. From there a bus or a local train to Blagoveshchensk, 2–2.5 hours. For those travelling for the journey, not the speed.`,
  'Из Китая, через Амур': `From China, across the Amur`,
  'Автомост Россия–Китай у Кани-Кургана с пассажирскими автобусами, летом — паром, зимой — понтонная переправа. Первая в мире трансграничная канатка Благовещенск–Хэйхэ: запуск намечен на конец 2026 года, 6–8 минут над границей.': `The Russia–China road bridge at Kani-Kurgan with passenger buses; a ferry in summer, a pontoon crossing in winter. And the world's first cross-border cable car, Blagoveshchensk–Heihe, due to open in late 2026 — 6–8 minutes over the border.`,
  'Сколько стоит': `What it costs`,
  'Ориентиры на одного человека': `Ballpark figures, per person`,
  'Перелёт Москва ⇄ Благовещенск': `Moscow ⇄ Blagoveshchensk flight`,
  'Субсидированный тариф, в одну сторону': `Subsidised fare, one way`,
  'Обед в китайском кафе': `Lunch at a Chinese café`,
  'Ужин с амурской рыбой': `Dinner with Amur fish`,
  'Музей, вход': `Museum admission`,
  'День в Хэйхэ (нужен загран)': `A day in Heihe (passport needed)`,
  'Экскурсия на космодром Восточный': `Vostochny Cosmodrome tour`,
  'Субсидированный тариф — для молодёжи, пенсионеров, многодетных семей и жителей Дальнего Востока; продажа на год открывается в декабре и билеты быстро разбирают. Цена перелёта сильно зависит от даты и глубины покупки. Проживание и суточные посчитает конструктор маршрута ниже — под ваш бюджет, сезон и число ночей.': `The subsidised fare is for young people, pensioners, large families and residents of the Far East; the year's tickets go on sale in December and sell out fast. Airfare depends heavily on the date and how far ahead you book. Lodging and daily costs are worked out by the trip planner below — around your budget, season and number of nights.`,

  /* сезоны */
  'Декабрь — февраль': `December – February`,
  'Зима': `Winter`,
  'Амур встаёт, и по льду открывают понтонную переправу в Китай. Каток на набережной, огни Хэйхэ напротив, пустые музеи. Морозы сухие, но серьёзные — экипировка нужна честная.': `The Amur freezes and a pontoon crossing to China opens over the ice. A rink on the embankment, Heihe's lights across the river, empty museums. The cold is dry but serious — bring proper gear.`,
  'для смелых': `for the bold`,
  'Март — май': `March – May`,
  'Весна': `Spring`,
  'Ледоход на Амуре': `Ice drift on the Amur`,
  'Главное зрелище сезона — ледоход, обычно в конце апреля (в 2026-м лёд между Благовещенском и Хэйхэ тронулся 19 апреля, раньше срока). Город оживает, туристов ещё мало, цены спокойные.': `The season's big spectacle is the ice drift, usually in late April (in 2026 the ice between Blagoveshchensk and Heihe broke on 19 April, ahead of schedule). The city wakes up, tourists are still few, prices are calm.`,
  'ледоход': `ice drift`,
  'Июнь — август': `June – August`,
  'Лето': `Summer`,
  'Лето<span class="sea-now">сейчас</span>': `Summer<span class="sea-now">now</span>`,
  'Набережная, теплоходы, фонтаны. Краснокнижные лотосы Комарова у Ивановки цветут с середины июля, пик — начало августа. Самый людный сезон и самый дождливый: июль — месяц осадков.': `The embankment, riverboats, fountains. The protected Komarov lotuses near Ivanovka bloom from mid-July, peaking in early August. The busiest season, and the wettest: July is the rainy month.`,
  'лучшее время': `best time`,
  'Сентябрь — ноябрь': `September – November`,
  'Осень': `Autumn`,
  '«Амурская осень»': `"Amur Autumn"`,
  'В сентябре в городе кинофестиваль: премьеры, театр, звёзды на набережной. Золотая тайга вокруг, комфортное тепло в начале сезона и заметно меньше людей, чем летом.': `In September the city hosts a film festival: premieres, theatre, stars on the embankment. Golden taiga all around, comfortable warmth early in the season, and far fewer people than in summer.`,
  'фестивали': `festivals`,

  /* Хэйхэ — виза, способы */
  'Виза не нужна — но поездка не бесплатная': `No visa needed — but the trip isn't free`,
  'С 15 сентября 2025 года россияне въезжают в Китай без визы на срок до 30 дней; в мае 2026-го режим продлили до 31 декабря 2027 года. Нужен только загранпаспорт, действующий ещё минимум 6 месяцев — ни приглашения, ни брони отеля, ни справок. Бесплатна именно виза: за саму переправу через Амур платить придётся, и это основная статья расходов.': `Since 15 September 2025 Russians enter China visa-free for up to 30 days; in May 2026 the arrangement was extended to 31 December 2027. All you need is a passport valid for at least 6 more months — no invitation, hotel booking or paperwork. It's the visa that's free: the crossing over the Amur itself is paid, and that's the main expense.`,
  'Теплоходом': `By riverboat`,
  'навигация · май – октябрь': `season · May – October`,
  'Классика: 10–15 минут по воде плюс формальности. Отправления из Благовещенска в 10:00, 12:00, 14:00 и 16:00 по амурскому времени. Туда 3 780 ₽, обратно 2 520 ₽. В межсезонье, когда лёд ещё не встал, ходят суда на воздушной подушке — дороже.': `The classic option: 10–15 minutes on the water plus formalities. Departures from Blagoveshchensk at 10:00, 12:00, 14:00 and 16:00 Amur time. 3,780 ₽ over, 2,520 ₽ back. In the off-season, before the ice sets, hovercraft run — pricier.`,
  'Автобусом по мосту': `By bus over the bridge`,
  'круглый год': `year-round`,
  'Через первый автомост Россия–Китай. Первый рейс от автовокзала «Амурассо» в 07:30, в Хэйхэ в 09:50; последний из Благовещенска — в 14:10. Около 2 650 ₽ в одну сторону, в пути ~2 ч 20 мин вместе с границей. Зимой работает и понтонная переправа.': `Over the first Russia–China road bridge. First departure from the "Amurasso" coach station at 07:30, in Heihe by 09:50; last one out of Blagoveshchensk at 14:10. About 2,650 ₽ one way, ~2 h 20 min including the border. In winter a pontoon crossing runs too.`,
  'Канатной дорогой': `By cable car`,
  'запуск — конец 2026': `opening — late 2026`,
  'Первая в мире трансграничная канатка через государственную границу. Кабины до 110 человек, 6–8 минут над Амуром. Канат через реку натянули в июле 2026-го, запуск намечен на конец года — цены пока не объявлены.': `The world's first cross-border cable car over a state frontier. Cabins hold up to 110 people, 6–8 minutes above the Amur. The cable was strung across the river in July 2026; opening is set for the end of the year — fares not yet announced.`,
  'Экономика поездки': `The cost of a trip`,
  'Прикиньте бюджет на свою компанию': `Estimate the budget for your group`,
  'Как добираетесь': `How you travel`,
  'Теплоход': `Riverboat`,
  'май – октябрь': `May – October`,
  'Автобус': `Bus`,
  'Сколько человек': `How many people`,
  'Ночёвок в Хэйхэ': `Nights in Heihe`,
  'Уровень гостиницы': `Hotel level`,
  'Бюджет': `Budget`,
  'от 1 285 ₽': `from 1,285 ₽`,
  '3 звезды': `3 stars`,
  'Центр': `Central`,
  'от 3 870 ₽': `from 3,870 ₽`,
  'На еду и покупки, в день': `Food and shopping, per day`,
  'Как проходит день': `How the day goes`,
  'Хэйхэ вблизи': `Heihe up close`,
  'Отели и торговые улицы — в паре минут от причала': `Hotels and shopping streets — minutes from the pier`,
  'Зелёный город': `A green city`,
  'Велодорожки и парки на улицах Хэйхэ': `Bike lanes and parks along Heihe's streets`,
  'Время назад на час': `An hour back in time`,
  'Хэйхэ живёт по пекинскому времени, Благовещенск — по амурскому. Пересекая Амур, вы отматываете час назад, а возвращаясь — теряете. Расписание переправ — по амурскому.': `Heihe runs on Beijing time, Blagoveshchensk on Amur time. Crossing the river you gain an hour; coming back you lose it. Crossing timetables are in Amur time.`,
  'Торгуйтесь': `Haggle`,
  'На рынках и в торговых центрах цена начальная, а не окончательная. Обычная практика — сбить 10–30%. Без торга вы просто переплатите.': `In markets and malls the price is a starting point, not a final one. Knocking off 10–30% is normal. Without haggling you simply overpay.`,
  'Обратно дольше': `The way back is slower`,
  'Туда границу проходят быстро, обратно — медленнее: досмотр покупок. Закладывайте запас и не берите последний рейс впритык.': `The border is quick on the way in, slower on the way out — they inspect your shopping. Leave a buffer and don't cut it close with the last departure.`,
  'Зачем едут': `Why people go`,
  'Рынки и техника, дунбэйская кухня, спа и массаж, набережная с видом на Россию, парк водно-болотных угодий. Отдельная история — стоматология и косметология «под ключ».': `Markets and electronics, Dongbei food, spas and massage, a promenade looking back at Russia, a wetlands park. And a category of its own — all-in-one dentistry and cosmetic procedures.`,
  'Цены — ориентиры на июль 2026 по данным перевозчиков, сервисов бронирования и городских СМИ Приамурья; тарифы и расписание меняются, перед поездкой сверяйтесь с перевозчиком. Расчёт не включает страховку и обмен валюты. Обратные рейсы уточняйте отдельно — их расписание корректируют по погоде и загрузке.': `Prices are ballpark figures for July 2026 from carriers, booking services and Amur-region local media; fares and schedules change, so check with the carrier before you go. The estimate excludes insurance and currency exchange. Confirm return departures separately — their timing is adjusted for weather and demand.`,

  /* канатка */
  'Готовность около 90% · трос через Амур протянут 2 июля 2026': `About 90% complete · the cable was strung across the Amur on 2 July 2026`,
  'дней до декабря 2026 — месяца, когда объект обещают довести до готовности к эксплуатации<br><em>ориентир по Хэйлунцзянскому ТВ (июль 2026); сроки уже переносили — перед поездкой перепроверьте</em>': `days until December 2026 — the month the project is promised to be ready for operation<br><em>per Heilongjiang TV (July 2026); the date has slipped before — double-check before your trip</em>`,
  'Терминал на «Золотой миле» и кабина над Амуром': `The terminal on the "Golden Mile" and a cabin above the Amur`,
  'Проектная визуализация: терминальная станция по проекту бюро UNStudio, победителя международного конкурса': `Concept render: the terminal station designed by UNStudio, winner of the international competition`,
  'длина трассы над Амуром и государственной границей': `length of the line above the Amur and the state border`,
  'в пути между двумя странами': `travel time between the two countries`,
  'вместимость каждой из двух кабин': `capacity of each of the two cabins`,
  'пропускная способность в одну сторону': `one-way capacity per hour`,
  'Что будет в терминале': `What the terminal will hold`,
  'Четырёхэтажное здание на набережной: пограничный и таможенный контроль, магазины duty free, торговая галерея и ресторан с видом на Амур. Работать планируют ежедневно с 07:00 до 23:00. Стоимость проекта — около 10 млрд рублей.': `A four-storey building on the embankment: border and customs control, duty-free shops, a retail gallery and a restaurant overlooking the Amur. Planned hours are 07:00 to 23:00 daily. The project costs around 10 billion roubles.`,
  'июль 2019': `July 2019`,
  'Начало строительства на российском берегу': `Construction begins on the Russian bank`,
  'Смонтирована опора высотой 64 метра, поднят корпус терминала': `A 64-metre support tower is erected, the terminal shell goes up`,
  'январь 2026': `January 2026`,
  'Китайская часть готова на 97%, идёт монтаж оборудования': `The Chinese side is 97% done, equipment is being installed`,
  '2 июля 2026': `2 July 2026`,
  'Тросы протянуты через Амур — мы сейчас здесь': `The cables are strung across the Amur — we're here now`,
  'декабрь 2026': `December 2026`,
  'Пусконаладка и готовность к эксплуатации': `Commissioning and readiness for operation`,
  'О сроках честно: их уже переносили. Сначала запуск обещали на весну 2026-го, потом говорили о тестовом пуске в июле. По самым свежим данным — Хэйлунцзянское телевидение, 5 июля 2026 года — пусконаладочные работы пройдут в конце года, а к эксплуатации объект будет готов в декабре. Так что если планируете проехать над Амуром — рассчитывайте на зиму, а не на осень.<br><br>Цену билета официально не объявляли. В публикациях называют ориентир около 3 000 ₽ за поездку туда и обратно, но это оценка, а не тариф.': `Honestly about the timing: it has slipped before. First the opening was promised for spring 2026, then a test run in July. Per the latest — Heilongjiang TV, 5 July 2026 — commissioning will happen at the end of the year, and the facility will be ready for operation in December. So if you're planning to ride over the Amur, count on winter, not autumn.<br><br>The fare hasn't been announced officially. Reports cite a ballpark of about 3,000 ₽ for a round trip, but that's an estimate, not a tariff.`,
  'Пока канатка не открылась, в Китай ходят теплоходы и автобусы по мосту — как добраться и во что обойдётся, посчитано в блоке <a href="#heihe" style="color:#e79fc9;text-decoration:underline;text-underline-offset:3px">«Две страны за один день»</a> выше.': `Until the cable car opens, riverboats and buses over the bridge run to China — how to get there and what it costs is worked out in the <a href="#heihe" style="color:#e79fc9;text-decoration:underline;text-underline-offset:3px">"Two countries in a day"</a> block above.`,

  /* планировщик — форма */
  'Состав': `Group`,
  'Соло': `Solo`,
  'Свобода маршрута': `A route of your own`,
  'Пара': `Couple`,
  'Отдых вдвоём': `A trip for two`,
  'Друзья': `Friends`,
  'Компания': `A group`,
  'Семья': `Family`,
  'С детьми': `With kids`,
  'Сезон': `Season`,
  'Лёд на Амуре': `Ice on the Amur`,
  'Ледоход, тепло': `Ice drift, warming up`,
  'Амур, лотосы': `The Amur, lotuses`,
  'Сколько дней': `How many days`,
  'Что интересно': `What interests you`,
  'Река, Амур': `River, the Amur`,
  'Гастрономия': `Food`,
  'Актив': `Active`,
  'Отдых': `Leisure`,
  'Китай, казачество': `China, Cossacks`,
  'Рыбалка': `Fishing`,
  'Город, музеи': `City, museums`,
  'Бюджет на одного в день': `Budget per person, per day`,
  'Собрать маршрут →': `Build the route →`,
  'Здесь появится маршрут': `Your route appears here`,
  'Заполните анкету слева — алгоритм подберёт активности по дням, построит таймлайн и посчитает бюджет с разбивкой.': `Fill in the form on the left — the planner will pick activities day by day, build a timeline and break down the budget.`,

  /* история — 4 эпохи */
  'Албазин — первый форпост на Амуре': `Albazin — the first outpost on the Amur`,
  'В 1651 году отряд Ерофея Хабарова занял городок даурского князя Албазы — так возник Албазинский острог, первое русское поселение на Амуре. В 1685–1686 годах горстка казаков дважды держала оборону против многократно превосходящих цинских войск.': `In 1651 Yerofey Khabarov's party took the town of the Daur prince Albaza — and so the Albazin fort arose, the first Russian settlement on the Amur. In 1685–1686 a handful of Cossacks twice held out against vastly larger Qing forces.`,
  '«Из нескольких сотен защитников второй осады Албазина в живых осталось около двадцати казаков — но крепость не сдалась.»': `"Of the several hundred defenders of Albazin's second siege, some twenty Cossacks survived — but the fort did not fall."`,
  'Рождение города и возвращение Амура': `The city's birth and the return of the Amur`,
  'На слиянии Зеи и Амура основан Усть-Зейский пост. Муравьёв-Амурский подписал в 1858 году Айгунский договор, вернувший Приамурье России. В том же году пост стал городом Благовещенском — в честь «благой вести» о возвращении земель.': `At the confluence of the Zeya and the Amur the Ust-Zeysky post was founded. In 1858 Muravyov-Amursky signed the Treaty of Aigun, returning the Amur region to Russia. That same year the post became the city of Blagoveshchensk — named for the "good news" of the lands' return.`,
  '«Город назвали Благовещенском, потому что возвращение Амура России сочли настоящей „благой вестью“.»': `"The city was named Blagoveshchensk because the Amur's return to Russia was seen as truly 'good news' (blagaya vest')."`,
  'конец XIX – нач. XX в.': `late 19th – early 20th c.`,
  '«Амурский Чикаго» — золото и купцы': `The "Amur Chicago" — gold and merchants`,
  'Золотая лихорадка на приисках Зеи и беспошлинная торговля с Китаем сделали Благовещенск богатейшим городом востока. Купеческие капиталы подняли особняки, банки, электростанцию и водопровод раньше многих губернских столиц.': `A gold rush on the Zeya diggings and duty-free trade with China made Blagoveshchensk the richest city in the east. Merchant capital raised mansions, banks, a power station and running water earlier than in many provincial capitals.`,
  '«На рубеже веков Благовещенск по числу купеческих капиталов соперничал со столичными городами.»': `"At the turn of the century Blagoveshchensk rivalled the capital cities in the number of merchant fortunes."`,
  'XX – XXI в.': `20th – 21st c.`,
  'Приграничный город — от погранзоны до космоса': `A border city — from a closed zone to space`,
  'В советские годы Благовещенск был закрытой погранзоной. Сегодня это главные «ворота» в Китай: автомост через Амур (2022) и первая в мире трансграничная канатка в Хэйхэ. А в 180 км началась новая эпоха — космодром Восточный.': `In the Soviet era Blagoveshchensk was a closed border zone. Today it's the main "gateway" to China: a road bridge over the Amur (2022) and the world's first cross-border cable car to Heihe. And 180 km away a new era began — the Vostochny Cosmodrome.`,
  '«Благовещенск и Хэйхэ разделяет всего около 750 метров воды — единственная в мире пара городов-соседей двух стран, стоящих так близко.»': `"Just about 750 metres of water separate Blagoveshchensk and Heihe — the world's only pair of neighbouring cities of two countries standing so close."`,

  /* слайдер до/после */
  'Та же арка — сто двадцать лет спустя': `The same arch — a hundred and twenty years apart`,
  'Потяните ползунок. Слева — Триумфальная арка на снимке 1904 года, справа — она же в наши дни. Оригинал 1891 года не пережил XX век: нынешнюю арку восстановили в 2005-м по старым фотографиям.': `Drag the slider. On the left, the Triumphal Arch in a photo from 1904; on the right, the same arch today. The 1891 original did not survive the 20th century: the present arch was rebuilt in 2005 from old photographs.`,
  'наши дни': `today`,
  'Слева: фото 1904 года из книги Элима Демидова, общественное достояние. Справа: фото 2013 года, Sharon Hahn Darlin, CC BY 2.0 — обе с Wikimedia Commons. Нынешняя арка воссоздана в 2005 году по фотографиям оригинала.': `Left: a 1904 photo from Elim Demidov's book, public domain. Right: a 2013 photo, Sharon Hahn Darlin, CC BY 2.0 — both from Wikimedia Commons. The present arch was recreated in 2005 from photographs of the original.`,

  /* кухня */
  'Амурский сазан и уха': `Amur carp and fish soup`,
  'Речная рыба Амура — сазан, верхогляд, косатка-скрипун — на гриле или в наваристой ухе. Порция ~500–900 ₽.': `Amur river fish — carp, skygazer, catfish — grilled or in a rich fish soup. A portion is ~500–900 ₽.`,
  'Калуга и амурский осётр': `Kaluga and Amur sturgeon`,
  'Легендарные гиганты Амура. Дикий вылов запрещён — к столу подают аквакультурную рыбу и икру (от 1 500 ₽).': `The Amur's legendary giants. Wild catch is banned — farmed fish and caviar are served instead (from 1,500 ₽).`,
  'Го-бао-жоу по-хэйхэйски': `Guo bao rou, Heihe style`,
  'Свинина в кисло-сладком кляре — визитка дунбэйской кухни. Сотни китайских кафе, чек 400–800 ₽.': `Sweet-and-sour battered pork — the signature of Dongbei cooking. Hundreds of Chinese cafés, a bill of 400–800 ₽.`,
  'Папоротник-орляк': `Bracken fern`,
  'Таёжный дикорос, маринованный или обжаренный с мясом «по-корейски». Хрустящая закуска.': `A wild taiga plant, pickled or stir-fried with meat "Korean style". A crunchy starter.`,
  'Соя и тофу': `Soy and tofu`,
  'Амурская область — «соевая столица» России. Соевое молоко, тофу, окара, соусы — специалитет и сувенир.': `The Amur region is Russia's "soy capital". Soy milk, tofu, okara, sauces — both a specialty and a souvenir.`,
  'Амурский таёжный мёд': `Amur taiga honey`,
  'Липовый и разнотравный мёд Приамурья — популярный гостинец с городских рынков и ярмарок.': `Linden and wildflower honey from the Amur region — a favourite gift from the city's markets and fairs.`,
  'Дикоросы: лимонник, брусника': `Wild harvest: schisandra, lingonberry`,
  'Морсы, настойки, варенья из таёжных ягод. Лимонник — местный природный «энергетик».': `Fruit drinks, tinctures and jams from taiga berries. Schisandra is the local natural "energy drink".`,
  'Казачий рыбник': `Cossack fish pie`,
  'Закрытый рыбный пирог амурского казачества с речной рыбой. Сытно и по-домашнему.': `A sealed river-fish pie of the Amur Cossacks. Hearty and homemade.`,

  /* факты */
  '750 метров — и ты в другом мире': `750 metres — and you're in another world`,
  'С набережной видно, как живёт китайский Хэйхэ. <b>Единственная в мире пара городов двух стран</b>, стоящих так близко: свои язык, кухня, деньги и уклад — через одну реку.': `From the embankment you can watch Chinese Heihe go about its day. <b>The world's only pair of cities of two countries</b> standing this close: their own language, food, money and way of life — across a single river.`,
  'Почти все машины — «праворульки»': `Nearly every car is right-hand drive`,
  'Около <b>90% автомобилей праворульные</b>, и таксист сидит справа. Дальневосточная привычка, к которой приезжие привыкают буквально за день.': `About <b>90% of cars are right-hand drive</b>, and the taxi driver sits on the right. A Far Eastern habit that visitors get used to within a day.`,
  'Памятник Челноку': `A monument to the shuttle trader`,
  'В 90-е «кирпичи» — люди-перевозчики — таскали через Амур <b>больше 30 тонн товара в день</b>. Челночный бизнес держал город на плаву, когда экономика стояла. Ему поставили памятник.': `In the 1990s the "bricks" — human couriers — hauled <b>over 30 tonnes of goods a day</b> across the Amur. Shuttle trading kept the city afloat when the economy stalled. It got its own monument.`,
  'Юань всё перевернул': `The yuan flipped everything`,
  'Когда юань стоил 3–5 ₽, русские ездили в Хэйхэ за всем подряд. Теперь юань 12–13 ₽ — и <b>уже китайцы едут скупать в Благовещенск</b>.': `When the yuan cost 3–5 ₽, Russians went to Heihe for everything. Now the yuan is 12–13 ₽ — and <b>it's the Chinese who come to shop in Blagoveshchensk</b>.`,
  'Пёс Дружок с набережной': `Druzhok, the embankment dog`,
  'В наводнение 2013-го Амур поднялся до рекордных 822 см (больше 8 метров) и затопил 126 населённых пунктов области. Пёс несколько дней ждал хозяев на крыльце затопленного дома — теперь <b>бронзовый Дружок «охраняет весь город»</b>.': `In the 2013 flood the Amur rose to a record 822 cm (over 8 metres) and swamped 126 settlements in the region. A dog waited days for his owners on the porch of a flooded house — now <b>a bronze Druzhok "guards the whole city"</b>.`,
  'Арку построили за полгода': `The arch went up in half a year`,
  'Триумфальную арку возвели к приезду цесаревича Николая. Такие же ставили в Хабаровске и Владивостоке, но <b>благовещенская — самая большая</b>.': `The Triumphal Arch was raised for the visit of Tsarevich Nicholas. Similar ones went up in Khabarovsk and Vladivostok, but <b>Blagoveshchensk's is the largest</b>.`,
  'Канатка из страны в страну': `A cable car from country to country`,
  'Первая в мире трансграничная канатная дорога через Амур. Кабины — <b>до 110 человек каждая</b>, и над рекой между двумя государствами всего несколько минут.': `The world's first cross-border cable car over the Amur. Cabins hold <b>up to 110 people each</b>, and it's just a few minutes over the river between two states.`,
  'Балалайка встречает пипу': `A balalaika meets a pipa`,
  'В парке Дружбы за китайской пагодой стоит советская панелька, а рядом — <b>памятник русской балалайке и китайской пипе</b>. Мир, дружба, музыка.': `In Friendship Park, behind a Chinese pagoda stands a Soviet apartment block, and beside it — <b>a monument to the Russian balalaika and the Chinese pipa</b>. Peace, friendship, music.`,
  'За здоровьем — в Китай': `To China for your health`,
  'В Хэйхэ летят со всей России за <b>стоматологией и бьюти-процедурами «под ключ»</b>: дешевле, с гарантией и всем спектром услуг в одном центре.': `People fly to Heihe from across Russia for <b>all-in-one dentistry and beauty treatments</b>: cheaper, guaranteed, and the full range of services in one centre.`,
  'Порция — минимум 400 грамм': `A portion is at least 400 grams`,
  'В китайских кафе блюда заказывают <b>на всех и ставят в центр стола</b>. Меньше 400 г не бывает — вдвоём осилить три блюда почти нереально.': `In Chinese cafés dishes are ordered <b>for everyone and placed in the middle of the table</b>. Nothing comes under 400 g — two people finishing three dishes is nearly impossible.`,
  'Когда на набережной стояли пушки': `When cannon stood on the embankment`,
  'В 1900-м, во время Боксёрского восстания в Китае, граница у города на пару месяцев стала <b>линией вооружённого противостояния</b>. Сегодня на том же берегу — прогулки и фонтаны.': `In 1900, during the Boxer Rebellion in China, the border by the city briefly became <b>a line of armed standoff</b> for a couple of months. Today that same bank has strolls and fountains.`,
  'Фонтан, по которому ходят': `A fountain you walk through`,
  'На площади Ленина — <b>крупнейший в Евразии пешеходный светомузыкальный фонтан</b>: почти 3 000 м² струй бьют прямо из мостовой. Днём в нём носятся дети, вечером — водно-световое шоу; сезон открывают 1 мая.': `On Lenin Square stands <b>Eurasia's largest walk-through light-and-music fountain</b>: nearly 3,000 m² of jets rise straight from the pavement. By day children dash through it; by night, a water-and-light show. The season opens on 1 May.`,
  'Солнце здесь — норма': `Sunshine is the norm here`,
  'По климатическим справочникам у Благовещенска <b>около 186 солнечных дней в году</b> — больше половины календаря. Июль выдаёт до 23 солнечных дней, а морозная зима — это почти всегда ясное небо.': `By climate references Blagoveshchensk has <b>about 186 sunny days a year</b> — more than half the calendar. July delivers up to 23 sunny days, and the frosty winter is almost always clear-skied.`,
  'Нейросеть-цензор в музее': `An AI censor in the museum`,
  'В музее спросили про тот конфликт у китайского DeepSeek — он <b>вежливо отказался отвечать</b>. ChatGPT рассказал всё. Один вопрос — разные страны, разные ответы.': `At the museum they asked China's DeepSeek about that conflict — it <b>politely declined to answer</b>. ChatGPT told all. One question, different countries, different answers.`,

  /* FAQ */
  'Нужна ли виза, чтобы съездить в Хэйхэ?': `Do I need a visa to visit Heihe?`,
  'Нет. С 15 сентября 2025 года россияне въезжают в Китай <b>без визы на срок до 30 дней</b>, в мае 2026-го режим продлили до конца 2027 года. Нужен только загранпаспорт, действующий ещё минимум 6 месяцев, — без приглашений, броней и справок. Сама переправа платная: теплоходом около 6 300 ₽ туда-обратно, автобусом по мосту около 5 300 ₽.': `No. Since 15 September 2025 Russians enter China <b>visa-free for up to 30 days</b>; in May 2026 this was extended to the end of 2027. You only need a passport valid for at least 6 more months — no invitations, bookings or paperwork. The crossing itself is paid: about 6,300 ₽ round trip by riverboat, about 5,300 ₽ by bus over the bridge.`,
  'Как добраться до Благовещенска из Москвы?': `How do I get to Blagoveshchensk from Moscow?`,
  'Прямым рейсом — 5 595 км, от 7 ч 25 мин. Билеты от ~10 000 ₽ в одну сторону при ранней покупке; для молодёжи, пенсионеров, многодетных и жителей Дальнего Востока есть субсидированный тариф 9 700 ₽. Поездом — до Белогорска на Транссибе (~110 км), дальше автобус или пригородный, 2–2,5 часа. Разница с Москвой +6 часов.': `By direct flight — 5,595 km, from 7 h 25 min. Tickets from ~10,000 ₽ one way if booked early; young people, pensioners, large families and Far East residents get a subsidised fare of 9,700 ₽. By train — to Belogorsk on the Trans-Siberian (~110 km), then a bus or local train, 2–2.5 hours. Moscow is 6 hours behind.`,
  'Когда лучше ехать в Благовещенск?': `When is the best time to visit Blagoveshchensk?`,
  'Универсальный ответ — <b>лето</b>: набережная, теплоходы, лотосы, +22…+28 °C. Но у каждого сезона свой козырь: в конце апреля — ледоход на Амуре, в сентябре — кинофестиваль «Амурская осень» и бархатное тепло, зимой — замёрзшая река, каток и огни Хэйхэ через лёд при −15…−27 °C.': `The safe answer is <b>summer</b>: the embankment, riverboats, lotuses, +22…+28 °C. But each season has its trump card: late April brings the ice drift on the Amur, September the "Amur Autumn" film festival and mellow warmth, winter a frozen river, a skating rink and Heihe's lights across the ice at −15…−27 °C.`,
  'Когда цветут лотосы и где их смотреть?': `When do the lotuses bloom, and where to see them?`,
  'С середины июля до середины августа, пик — начало августа. Ближайшее к городу место — озеро у села Ивановка, около часа на машине. Лотос Комарова — краснокнижный: рвать нельзя, фотографировать — сколько угодно.': `From mid-July to mid-August, peaking in early August. The closest spot to the city is a lake near the village of Ivanovka, about an hour by car. The Komarov lotus is protected: no picking, but photograph all you like.`,
  'Правда, что почти все машины — праворульные?': `Is it true that nearly all cars are right-hand drive?`,
  'Правда: около <b>90% автомобилей в городе с правым рулём</b>, японский автопром — дальневосточная классика. Таксист будет сидеть справа. Приезжие привыкают за день, а для местных это просто норма.': `True: about <b>90% of the city's cars are right-hand drive</b> — Japanese vehicles are a Far Eastern staple. Your taxi driver will sit on the right. Visitors adjust in a day; for locals it's just normal.`,
  'Сколько стоит день в Хэйхэ?': `How much does a day in Heihe cost?`,
  'Ориентир на одного: переправа 5 300–6 300 ₽ туда-обратно, обед в китайском кафе 400–800 ₽, покупки — по аппетиту (торговаться обязательно, сбивают 10–30%). Итого день «посмотреть и поесть» — примерно 8–10 тысяч ₽. Ночёвка добавит от 1 300 ₽ за номер.': `Ballpark per person: the crossing 5,300–6,300 ₽ round trip, lunch at a Chinese café 400–800 ₽, shopping to taste (haggling is a must — 10–30% off). A "see and eat" day comes to roughly 8,000–10,000 ₽. A night's stay adds from 1,300 ₽ per room.`,
  'Когда откроется канатная дорога в Китай?': `When will the cable car to China open?`,
  'По данным на июль 2026-го — <b>декабрь 2026</b>: тросы через Амур протянуты, готовность около 90%, пусконаладка в конце года. Сроки уже переносили, так что перед поездкой стоит перепроверить. Пока работают теплоход и автобус по мосту.': `As of July 2026 — <b>December 2026</b>: the cables are strung across the Amur, it's about 90% complete, with commissioning at year's end. The date has slipped before, so double-check before your trip. For now the riverboat and the bridge bus are running.`,
  'Чем платить в Хэйхэ?': `How do I pay in Heihe?`,
  'Российские карты Visa и Mastercard в Китае не работают. Берите <b>наличные юани</b> — обменять можно в банках Благовещенска. В туристических местах Хэйхэ, ориентированных на россиян, часто принимают и рубли, но курс там хуже. Основной способ оплаты у самих китайцев — Alipay и WeChat Pay.': `Russian Visa and Mastercard don't work in China. Bring <b>cash yuan</b> — you can exchange it at banks in Blagoveshchensk. In Heihe's Russia-facing tourist spots roubles are often accepted too, but the rate is worse. The Chinese themselves mostly pay by Alipay and WeChat Pay.`,

  /* сторителлинг по набережной */
  '01 · старт': `01 · start`,
  'Триумфальная арка': `The Triumphal Arch`,
  'Отсюда начинается парадный выход к Амуру. Двадцатиметровую арку с двуглавыми орлами поставили в 1891-м к визиту цесаревича Николая, воссоздали в 2005-м. За ней открывается река и китайский берег.': `The grand approach to the Amur starts here. The twenty-metre arch with double-headed eagles was raised in 1891 for Tsarevich Nicholas's visit and recreated in 2005. Beyond it open the river and the Chinese bank.`,
  '<svg viewBox="0 0 24 24"><path d="M12 5v14M6 13l6 6 6-6"></path></svg>листайте вниз — идём дальше': `<svg viewBox="0 0 24 24"><path d="M12 5v14M6 13l6 6 6-6"></path></svg>scroll down — let's go on`,
  'Памятник Муравьёву-Амурскому': `The Muravyov-Amursky monument`,
  'Основатель города и «собиратель» Приамурья стоит на набережной и смотрит на Амур с Китаем за ним. Именно он подписал Айгунский договор 1858 года, вернувший эти земли России.': `The city's founder and "gatherer" of the Amur region stands on the embankment, looking out at the Amur with China beyond. It was he who signed the 1858 Treaty of Aigun that returned these lands to Russia.`,
  'Лицом к Хэйхэ — 750 метров': `Facing Heihe — 750 metres`,
  'Здесь Амур сужается до 750 метров, и с парапета виден китайский Хэйхэ: высотки, набережная, вечерние огни. Единственная в мире пара городов двух стран, стоящих так близко, — глаза в глаза через реку.': `Here the Amur narrows to 750 metres, and from the parapet you can see Chinese Heihe: towers, a promenade, evening lights. The world's only pair of cities of two countries standing this close — eye to eye across the river.`,
  'Река': `River`,
  'Пёс Дружок': `Druzhok the dog`,
  'Бронзовый пёс на парапете — память о наводнении 2013 года, когда Амур поднялся выше 8 метров. Он несколько дней ждал хозяев на крыльце затопленного дома; теперь, по словам горожан, «охраняет весь город».': `A bronze dog on the parapet — a memory of the 2013 flood, when the Amur rose above 8 metres. He waited days for his owners on the porch of a flooded house; now, locals say, he "guards the whole city".`,
  '05 · финал': `05 · finale`,
  'Площадь Ленина и поющий фонтан': `Lenin Square and the singing fountain`,
  'Прогулка выводит к сердцу города: крупнейший в Евразии пешеходный светомузыкальный фонтан бьёт прямо из мостовой — почти 3 000 м² струй. Днём в нём носятся дети, вечером — водно-световое шоу под музыку.': `The walk leads to the city's heart: Eurasia's largest walk-through light-and-music fountain rises straight from the pavement — nearly 3,000 m² of jets. By day children dash through it; by night, a water-and-light show set to music.`,
  'Город': `City`,

  /* галерея — подписи */
  '01 · Речной вокзал': `01 · River terminal`,
  'Теплоходы уходят в Китай отсюда': `Riverboats to China leave from here`,
  '02 · Набережная Амура': `02 · The Amur embankment`,
  'Хэйхэ на том берегу': `Heihe on the far bank`,
  '03 · Собор Благовещения': `03 · Annunciation Cathedral`,
  'Семь золочёных куполов': `Seven gilded domes`,
  '04 · Мост через Амур': `04 · The bridge over the Amur`,
  'Первый автомост в Китай, стройка 2019-го': `The first road bridge to China, under construction in 2019`,
  '05 · Центр города': `05 · The city centre`,
  'Купеческий Благовещенск': `Merchant-era Blagoveshchensk`,
  '06 · Лотосы Комарова': `06 · Komarov lotuses`,
  'Цветут в июле у Ивановки': `Blooming in July near Ivanovka`,
  '07 · Космодром Восточный': `07 · Vostochny Cosmodrome`,
  'Первый пуск «Союза-2» · 180 км от города': `The first Soyuz-2 launch · 180 km from the city`,
  '08 · Муравьёв-Амурский': `08 · Muravyov-Amursky`,
  'Основатель города на набережной': `The city's founder on the embankment`,
  '09 · Площадь Ленина': `09 · Lenin Square`,
  'Пешеходный фонтан — крупнейший в Евразии': `A walk-through fountain — the largest in Eurasia`,

  /* футер — бренд */
  '<img class="logo" src="assets/logo-mark.png" alt="ИИщенко LAB" width="32" height="32">ИИщенко LAB': `<img class="logo" src="assets/logo-mark.png" alt="Iishchenko LAB" width="32" height="32">Iishchenko LAB`,

  /* --- 14. сотрудничество --- */
  '14 — сотрудничество': `14 — working together`,
  'Сайт делает <em>один человек</em><br>из Благовещенска': `This site is made by <em>one person</em><br>living in Blagoveshchensk`,
  'Гостевой дом, экскурсия, кафе, событие — напишите. Точку на карту и строку в афишу добавляю бесплатно, если приезжему это правда интересно. Рекламное размещение — отдельный разговор.': `A guesthouse, a tour, a cafe, an event — write to me. Adding a point to the map or a line to the events feed is free, as long as it is genuinely worth a visitor’s time. Paid placement is a separate conversation.`,
  'Объект на карту': `A place on the map`,
  'Гостевой дом, музей, смотровая точка, мастерская, баня на Амуре': `A guesthouse, a museum, a viewpoint, a workshop, a bathhouse on the Amur`,
  'Событие в афишу': `An event for the feed`,
  'Фестиваль, ярмарка, концерт, заезд, открытие сезона': `A festival, a fair, a concert, a race, a season opening`,
  'Экскурсии и гиды': `Tours and guides`,
  'Маршрут, который стоит показать человеку впервые в городе': `A route worth showing someone in the city for the first time`,
  'Приём групп': `Group travel`,
  'Туроператоры и организаторы поездок из других регионов и из Китая': `Tour operators and trip organisers from other regions and from China`,
  'Реклама и размещение': `Advertising and placement`,
  'Баннер, интеграция в раздел, отдельный спецпроект': `A banner, an integration inside a section, a dedicated project`,
  'Ошибка на сайте': `A mistake on the site`,
  'Цифра, дата или координата не сходятся — скажите, поправлю': `A figure, a date or a coordinate does not add up — tell me and I will fix it`,
  'Написать автору': `Write to the author`,
  'Заявка уходит мне в Telegram. Отвечаю обычно в тот же день.': `The message goes straight to my Telegram. I usually reply the same day.`,
  'Как вас зовут': `Your name`,
  'Telegram, телефон или почта': `Telegram, phone or email`,
  'Повод': `Topic`,
  'Что важно сказать сразу': `What matters to say right away`,
  'Другое': `Something else`,
  'Согласен на обработку данных на условиях <a href="privacy.html" target="_blank" rel="noopener">Политики</a>. Заявка идёт через сервисы за пределами России — подробности там же.': `I agree to my data being processed under the <a href="privacy.html" target="_blank" rel="noopener">Privacy Policy</a>. The message travels through services outside Russia — details are there too.`,
  'Отправить <span>→</span>': `Send <span>→</span>`,
  'Сотрудничество': `Working together`,
  'Факты сверены и обновлены 31 августа 2026': `Facts checked and updated on 31 August 2026`,

  /* подписи рядом с заголовками и начальные значения конструктора */
  '~6 суток': `~6 days`,
  'минуты': `minutes`,
  '7,5–8 ч': `7.5–8 h`,
  '2 чел.': `2 people`,
  '5 дн.': `5 days`,
  '3 выбрано': `3 selected`,
  '0 — одним днём': `0 — a day trip`,
  'скоро': `soon`,
  '~6 300 ₽': `~6,300 ₽`,
  '~5 300 ₽': `~5,300 ₽`,
  '2 500 ₽': `2,500 ₽`,
  '6 000 ₽': `6,000 ₽`,
  'Итого на поездку': `Trip total`,
  'на человека<b id="hh-per">—</b>': `per person<b id="hh-per">—</b>`,
  'Фото не загрузилось. Попробуйте обновить страницу.': `The photo did not load. Try reloading the page.`,
  'Вне маршрутов': `Off the beaten track`,
  'День вне маршрутов': `A day off the beaten track`,
  'Набережная Амура в Благовещенске': `The Amur embankment in Blagoveshchensk`,
  'Набережная Амура, где стоит памятник': `The Amur embankment, where the monument stands`,
  'Цветущий лотос': `A lotus in bloom`,
  'Площадь Ленина в Благовещенске': `Lenin Square in Blagoveshchensk`,
  'Амур и китайский берег': `The Amur and the Chinese bank`,
  'Свинина в кисло-сладком соусе — классика дунбэйской кухни': `Sweet-and-sour pork — a Dongbei classic`,
  'Мост Благовещенск — Хэйхэ зимой': `The Blagoveshchensk–Heihe bridge in winter`,
  'Триумфальная арка зимой': `The Triumphal Arch in winter`,
  'Триумфальная арка на набережной Амура': `The Triumphal Arch on the Amur embankment`,
  'Реконструкция амурозавра — ящера, найденного под Благовещенском': `A reconstruction of Amurosaurus, the reptile found near Blagoveshchensk`,
  'Благовещенск на старом снимке': `Blagoveshchensk in an old photograph`,
  'Большая улица и торговая площадь, XIX век': `Bolshaya Street and the trade square, 19th century`,
  'Благовещенск с китайского берега': `Blagoveshchensk seen from the Chinese bank`,
  'Триумфальная арка, Амур и высотки китайского Хэйхэ за рекой': `The Triumphal Arch, the Amur and the towers of Chinese Heihe across the river`,
  'Триумфальная арка зимой, в снегу': `The Triumphal Arch in winter, under snow`,
  'Триумфальная арка весной, цветущие деревья': `The Triumphal Arch in spring, trees in blossom`,
  'Триумфальная арка летом, зелень и синее небо': `The Triumphal Arch in summer, greenery and blue sky`,
  'Триумфальная арка осенью, золотая листва': `The Triumphal Arch in autumn, golden foliage`,
  'Солнечная улица Хэйхэ с гостиницей': `A sunny street in Heihe with a hotel`,
  'Зелёная улица Хэйхэ с велодорожкой': `A green street in Heihe with a bike lane`,
  'Терминал канатной дороги Благовещенск — Хэйхэ и кабина над Амуром, проектная визуализация': `The Blagoveshchensk–Heihe cable car terminal and a cabin above the Amur, a concept render`,
  'Триумфальная арка в Благовещенске в наши дни': `The Triumphal Arch in Blagoveshchensk today`,
  'Триумфальная арка на фотографии 1904 года': `The Triumphal Arch in a photograph from 1904`,
  'Теплоход у набережной Амура в Благовещенске': `A riverboat at the Amur embankment in Blagoveshchensk`,
  'Кафедральный собор Благовещения в Благовещенске': `The Annunciation Cathedral in Blagoveshchensk`,
  'Мост через Амур': `The bridge across the Amur`,
  'Центр города': `The city centre`,
  'Лотосы Комарова': `Komarov lotuses`,
  'Первый пуск с космодрома Восточный': `The first launch from the Vostochny Cosmodrome`,
  'Памятник Муравьёву-Амурскому в Благовещенске': `The Muravyov-Amursky monument in Blagoveshchensk`,
  'Пешеходный светомузыкальный фонтан на площади Ленина вечером': `The walk-through light-and-music fountain on Lenin Square in the evening`,
  'Теплоход туда-обратно': `Riverboat, round trip`,
  'Автобус туда-обратно': `Bus, round trip`,
  'Гостиница, бюджет': `Hotel, budget`,
  'Гостиница 3 звезды': `Hotel, 3 stars`,
  'Гостиница в центре': `Hotel in the centre`,
  'Еда и покупки': `Food and shopping`,
  'Как проходит первый день': `How the first day goes`,
  'день': `daytime`,
  'Первый теплоход из Благовещенска — по амурскому времени': `The first boat out of Blagoveshchensk — Amur time`,
  'Вы в Хэйхэ, а на часах 09:30: час в подарок из-за разницы поясов': `You are in Heihe and it is 09:30: an hour gained on the time difference`,
  'Набережная с видом на Россию, рынки, обед, спа или массаж': `The promenade facing Russia, markets, lunch, a spa or a massage`,
  'Последний теплоход обратно. Обратная граница идёт дольше — из-за досмотра покупок': `The last boat back. The border is slower on the way out — they inspect your shopping`,
  'Автобус от автовокзала «Амурассо», улица Чайковского 1/1': `The bus from the "Amurasso" coach station, 1/1 Chaykovskogo St`,
  'Прибытие в Хэйхэ вместе с прохождением границы — по местному 08:50': `Arrival in Heihe including border control — 08:50 local time`,
  'Торговые центры и рынки, дунбэйская кухня, парк водно-болотных угодий': `Shopping malls and markets, Dongbei food, the wetlands park`,
  'Последний рейс из Благовещенска — если едете вечером, это уже с ночёвкой': `The last departure from Blagoveshchensk — go later and you are staying the night`,
  'Осада Албазина на голландской гравюре XVII века': `The siege of Albazin in a 17th-century Dutch engraving`,
  '750 метров воды — и другая страна': `750 metres of water — and another country`,
  'Этот кадр снят с китайского берега: так город видят из Хэйхэ каждый день. Соберите маршрут под свои даты — или напишите, если вам есть что сюда добавить.': `This photo was taken from the Chinese bank: this is how the city looks from Heihe every day. Build a route around your dates — or write to me if you have something to add here.`,
  'Церемония кинофестиваля «Амурская осень»': `The "Amur Autumn" film festival ceremony`,
  'Экспозиция с динозаврами': `A dinosaur exhibition hall`,
  'Ледовый городок со снежными скульптурами на площади': `An ice town with snow sculptures on the square`,
  'Ростовые медведь и панда с девушками в кокошниках на Российско-Китайской ярмарке': `Bear and panda mascots with girls in kokoshniks at the Russia–China fair`,
  'Бронзовый пёс Дружок на парапете набережной, за Амуром — огни Хэйхэ': `The bronze dog Druzhok on the embankment parapet, the lights of Heihe across the Amur`,
  'XXIV фестиваль кино и театра «Амурская осень»': `The 24th "Amur Autumn" film and theatre festival`,
  'Главное культурное событие города: кинопремьеры, спектакли, творческие вечера и звёзды на набережной. В 2026-м показы идут с 12 по 19 сентября.': `The city’s main cultural event: film premieres, plays, evenings with the cast and stars out on the embankment. In 2026 the screenings run from 12 to 19 September.`,
  'ОКЦ · ул. Пионерская, 1': `Public and Cultural Centre · 1 Pionerskaya St`,
  'Премьера «Мера за меру» в театре драмы': `"Measure for Measure" premieres at the drama theatre`,
  'Шекспир на сцене одного из старейших театров Дальнего Востока (осн. 1883). Ближайшие показы — 2, 3 и 4 октября.': `Shakespeare on the stage of one of the oldest theatres in the Far East (founded 1883). The next performances are on 2, 3 and 4 October.`,
  'Театр драмы · ул. Ленина, 146': `Drama Theatre · 146 Lenina St`,
  'Ярмарки выходного дня': `Weekend farmers’ markets`,
  'Фермерские овощи, ягоды, мёд и молочное — прямо от производителей. Каждые выходные до 31 октября на двух площадках: у ОКЦ и возле ТЦ «Флагман».': `Vegetables, berries, honey and dairy straight from the farmers. Every weekend until 31 October at two sites: by the Public and Cultural Centre and next to the Flagman shopping centre.`,
  'Площадь ОКЦ · ул. Ленина, 100': `Public and Cultural Centre square · 100 Lenina St`,
  'Гастрофестиваль «Берега вкуса»': `The "Shores of Taste" food festival`,
  'Третий международный гастрофестиваль на набережной: 60 ресторанов и кафе, 80 павильонов, повара Дальнего Востока, Беларуси и Китая, мастер-классы и конкурсы. Идёт пять дней.': `The third international food festival on the embankment: 60 restaurants and cafes, 80 pavilions, chefs from the Russian Far East, Belarus and China, masterclasses and contests. It runs for five days.`,
  'Набережная Амура · от ул. Святителя Иннокентия до Калинина': `The Amur embankment · from Svyatitelya Innokentiya St to Kalinina St`,
  'Фестиваль идёт сразу на двух берегах Амура — в Благовещенске и Хэйхэ: концерты, выставка-продажа ремёсел, мастер-классы. В 2026-м прошёл шестнадцатый раз.': `The festival runs on both banks of the Amur at once — in Blagoveshchensk and Heihe: concerts, a craft fair, masterclasses. 2026 was its sixteenth year.`,
  'Набережная Амура и Хэйхэ': `The Amur embankment and Heihe`,
  'Открытие сезона фонтанов на площади Ленина': `The fountain season opens on Lenin Square`,
  'Крупнейший в Евразии пешеходный фонтан открывает сезон 1 мая. Вт–чт с 11:00 до 22:00, пт–вс до 23:00, светомузыка с 19:30; понедельник — технический день.': `Eurasia’s largest walk-through fountain opens its season on 1 May. Tue–Thu 11:00–22:00, Fri–Sun until 23:00, the light-and-music show from 19:30; Monday is a maintenance day.`,
  'Ледовый городок и главный каток': `The ice town and the main skating rink`,
  'Каток 40×30 метров, снежные горки и ледовые скульптуры на главной площади. Открывается во второй половине декабря и работает до весенней оттепели.': `A 40×30-metre rink, snow slides and ice sculptures on the main square. It opens in the second half of December and stays until the spring thaw.`,
  'Амур вскрывается на глазах у всего города — главное зрелище весны. Точной даты нет, всё решает погода: в 2026 году лёд между Благовещенском и Хэйхэ тронулся 19 апреля.': `The Amur breaks up in front of the whole city — the main spectacle of spring. There is no fixed date, the weather decides: in 2026 the ice between Blagoveshchensk and Heihe moved on 19 April.`,
  'Краснокнижный лотос цветёт на озёрах у села Ивановка с двадцатых чисел июля до конца августа. Самое пышное цветение длится 5–8 дней, смотреть лучше на рассвете. Рвать нельзя.': `The protected lotus blooms on the lakes near the village of Ivanovka from the third week of July until the end of August. The peak lasts 5–8 days and is best seen at dawn. Picking is forbidden.`,
  '«Культурный город на набережной»': `"A cultural city on the embankment"`,
  'Городской фестивальный формат, в 2026-м пошёл тринадцатый сезон: по выходным на набережных Амура и Зеи выставки живописи, ярмарки ремёсел, мастер-классы, шахматные турниры и выступления местных коллективов. Вход свободный, идёт с 1 мая до осени.': `A city festival format now in its thirteenth season: on weekends the embankments of the Amur and the Zeya host painting exhibitions, craft fairs, masterclasses, chess tournaments and performances by local groups. Free entry, from 1 May until autumn.`,
  'Набережные Амура и Зеи': `The Amur and Zeya embankments`,
  'Главное культурное событие города: кинопремьеры, спектакли, творческие вечера и звёзды на набережной. В 2026-м показы идут с 12 по 19 сентября — среди них «ФЕЛЛИНИ. 8½» театра имени Вахтангова 14 и 15 сентября.': `The city’s main cultural event: film premieres, plays, evenings with the cast and stars out on the embankment. In 2026 the screenings run from 12 to 19 September — among them "FELLINI. 8½" by the Vakhtangov Theatre on 14 and 15 September.`,
  '01 · Причал в Хэйхэ': `01 · Heihe pier`,
  'Сюда приходят теплоходы из Благовещенска': `This is where the boats from Blagoveshchensk arrive`,
  'Пассажирский теплоход у причала в китайском Хэйхэ': `A passenger boat at the pier in Heihe, China`,
  '02 · Вид с набережной': `02 · The view from the embankment`,
  'Ночью Хэйхэ зажигает иероглифы': `At night Heihe lights up its characters`,
  'Ночной Хэйхэ с набережной Благовещенска: высотки в красной подсветке отражаются в Амуре': `Heihe at night seen from the Blagoveshchensk embankment: towers in red light reflected in the Amur`,
  '05 · Торговый дом Чурина': `05 · The Churin trading house`,
  'Лучший магазин Восточной Сибири': `The finest store in Eastern Siberia`,
  'Торговый дом «И. Я. Чурин и Ко» в Благовещенске: жёлто-белый фасад с куполом и скульптурами': `The «I. Ya. Churin and Co» trading house in Blagoveshchensk: a yellow-and-white facade with a dome and sculptures`
};
