/* Английские переводы для «Амур Атласа». Ключ — русский оригинал (как в разметке),
   значение — английский. Движок i18n в index.html подменяет текст по совпадению ключа.
   Нет ключа — на сайте остаётся русский. Правьте свободно: сборки нет, файл статичный. */
window.EN = {
  '@title': `Blagoveshchensk: what to see, trips and a visit to Heihe — Amur Atlas guide`,
  '@desc': `A local's guide to Blagoveshchensk: 23 map points, a trip planner with a budget, how to cross into China's Heihe visa-free, the cable car, seasons and prices. Verified facts, July 2026.`,

  /* загрузчик + шапка */
  'Благовещенск': `Blagoveshchensk`,
  'Амур Атлас': `Amur Atlas`,
  'Зачем ехать': `Why go`,
  'Карта': `Map`,
  'События': `Events`,
  'Как доехать': `Getting there`,
  'Хэйхэ': `Heihe`,
  'Канатка': `Cable car`,
  'Маршрут': `Planner`,
  'История': `History`,
  'Любопытное': `Curious`,
  'Собрать маршрут': `Plan a trip`,

  /* hero */
  'Авторский гид · ИИщенко LAB': `An indie guide · Iishchenko LAB`,
  'Город на Амуре,<br>лицом к <span class="g">Китаю</span>': `A city on the Amur,<br>facing <span class="g">China</span>`,
  'Благовещенск — 750 метров воды до китайского Хэйхэ, купеческий «Амурский Чикаго», кухня двух стран, космодром Восточный и городское кладбище динозавров. Соберём маршрут под ваши интересы, сезон и бюджет.': `Blagoveshchensk sits just 750 metres of water from China's Heihe: a merchant-era "Amur Chicago", the cuisine of two countries, the Vostochny Cosmodrome, and a dinosaur graveyard right inside town. Let's build a trip around your interests, season and budget.`,
  'Собрать маршрут <span>→</span>': `Plan a trip <span>→</span>`,
  'Открыть карту': `Open the map`,
  '<b>23</b> точки на карте': `<b>23</b> points on the map`,
  '<b>4</b> эпохи истории': `<b>4</b> eras of history`,
  '<b>2</b> страны на тарелке': `<b>2</b> countries on a plate`,
  'RU ↔ CN<span>Амур · граница</span>': `RU ↔ CN<span>Amur · border</span>`,
  '<span class="dot"></span>Арка, Амур — и Хэйхэ за рекой': `<span class="dot"></span>The arch, the Amur — and Heihe beyond`,
  'воды до китайского Хэйхэ': `of water to China's Heihe`,
  'год основания города': `the year the city was founded`,
  'до космодрома Восточный': `to the Vostochny Cosmodrome`,
  'лет динозаврам под городом': `years — the dinosaurs beneath the city`,

  /* eyebrows секций */
  '01 — зачем ехать': `01 — why go`,
  '02 — интерактивная карта': `02 — interactive map`,
  '03 — что сейчас': `03 — what's on`,
  '04 — практика поездки': `04 — trip basics`,
  '05 — две страны за один день': `05 — two countries in a day`,
  '06 — скоро': `06 — coming soon`,
  '07 — конструктор маршрута': `07 — trip planner`,
  '08 — история': `08 — history`,
  '09 — гастрономия': `09 — food`,
  '10 — любопытное': `10 — curious facts`,
  '11 — вопросы': `11 — questions`,
  '12 — прогулка': `12 — a walk`,
  '13 — галерея': `13 — gallery`,

  /* заголовки и лиды секций */
  'Четыре разных Благовещенска<br>в одной <em>поездке</em>': `Four different Blagoveshchensks<br>in a single <em>trip</em>`,
  'За несколько дней — пройти по набережной лицом к китайскому мегаполису, застать купеческий «Амурский Чикаго», потрогать кости динозавров и увидеть, откуда стартуют ракеты.': `In a few days you can walk the embankment facing a Chinese metropolis, catch the merchant-era "Amur Chicago", touch dinosaur bones and see where the rockets launch.`,
  'Двадцать три <em>точки силы</em>': `Twenty-three <em>points of interest</em>`,
  'Кликайте на маркеры — описание и фото. Фильтруйте по категориям, чтобы спланировать день.': `Click a marker for a description and photo. Filter by category to plan your day.`,
  'События <em>прямо сейчас</em>': `Events <em>on right now</em>`,
  'Как добраться, когда ехать<br>и <em>сколько это стоит</em>': `How to get here, when to go<br>and <em>what it costs</em>`,
  'Благовещенск — 5 595 км от Москвы и шесть часовых поясов на восток. Разбираемся, чем сюда добираются, какой сезон под какие впечатления и на какие суммы ориентироваться.': `Blagoveshchensk is 5,595 km east of Moscow and six time zones away. Here's how people get here, which season fits which mood, and the sums to plan around.`,
  'Утром Россия,<br>днём <em>Китай</em>': `Russia in the morning,<br><em>China</em> by noon`,
  'Хэйхэ виден с набережной — 750 метров воды. Визы не нужно, хватает загранпаспорта: доехать до соседней страны отсюда проще и дешевле, чем до соседнего областного центра. Считаем, во что обойдётся.': `Heihe is right there from the embankment — 750 metres of water. No visa needed, just a passport: reaching the neighbouring country is easier and cheaper than the next region over. Let's price it out.`,
  'Первая в мире канатка<br><em>между двумя странами</em>': `The world's first cable car<br><em>between two countries</em>`,
  'Через Амур тянут канатную дорогу из России в Китай — такого нет больше нигде. Вместо парома и автобуса с формальностями — кабина и несколько минут над пограничной рекой. Стройку начали в 2019 году, сейчас она на финишной прямой.': `A cable car is being strung across the Amur from Russia to China — the only one of its kind anywhere. Instead of a ferry or a bus with formalities, a cabin and a few minutes above the border river. Construction began in 2019 and is now in its final stretch.`,
  'Соберём <em>персональный</em> маршрут': `Let's build your <em>personal</em> route`,
  'Алгоритм учитывает состав группы, сезон, интересы и бюджет — раскладывает активности по дням и прозрачно считает стоимость.': `The planner factors in your group, season, interests and budget — it spreads activities across days and prices everything transparently.`,
  'Четыре эпохи <em>на берегу Амура</em>': `Four eras <em>on the bank of the Amur</em>`,
  'Албазинский острог XVII века, рождение города при Муравьёве-Амурском, купеческий «Амурский Чикаго» и приграничный город XX–XXI веков — от погранзоны до моста и канатки в Китай.': `The 17th-century Albazin fort, the city's birth under Muravyov-Amursky, the merchant-era "Amur Chicago", and the 20th–21st-century border city — from a closed frontier to a bridge and a cable car into China.`,
  'Кухня <em>двух стран</em> на одном столе': `The cuisine of <em>two countries</em> on one table`,
  'Дунбэйская кухня соседнего Хэйхэ давно стала городской повседневностью, а рядом — амурская речная рыба, соя «соевой столицы» России, таёжные дикоросы и наследие казачества.': `The Dongbei cooking of neighbouring Heihe has long been everyday fare here — alongside Amur river fish, soy from Russia's "soy capital", wild taiga harvests and a Cossack heritage.`,
  'Неожиданный <em>Благовещенск</em>': `The <em>Blagoveshchensk</em> you don't expect`,
  'Факты, курьёзы и городские байки, которые превращают поездку в историю — из впечатлений тех, кто уже съездил на границу двух миров.': `Facts, oddities and city lore that turn a trip into a story — from those who've already been to this border between two worlds.`,
  'Что спрашивают <em>перед поездкой</em>': `What people ask <em>before the trip</em>`,
  'Короткие ответы на то, что обычно выясняют в первую очередь. Подробности — в блоках выше.': `Quick answers to the things people check first. Details are in the sections above.`,
  'Пройдёмся по <em>набережной</em>': `Let's walk the <em>embankment</em>`,
  'Пять шагов вдоль Амура — от Триумфальной арки до поющего фонтана. Листайте: карта идёт следом за вами.': `Five stops along the Amur — from the Triumphal Arch to the singing fountain. Scroll, and the map follows you.`,
  'Благовещенск <em>в кадре</em>': `Blagoveshchensk <em>in frame</em>`,
  'Набережная лицом к Китаю, Триумфальная арка, мост через Амур, космос и динозавры.': `The embankment facing China, the Triumphal Arch, the bridge across the Amur, space and dinosaurs.`,

  /* футер */
  'Готовы <em>увидеть</em> Благовещенск?': `Ready to <em>see</em> Blagoveshchensk?`,
  'К конструктору маршрута →': `To the trip planner →`,
  'Сайт создан жителем Благовещенска по собственной инициативе': `Made by a Blagoveshchensk local, on personal initiative`,
  'v2.0 · Амур Атлас · Благовещенск': `v2.0 · Amur Atlas · Blagoveshchensk`
};
