/* Английские переводы для «Амур Атласа». Ключ — русский оригинал (как в разметке),
   значение — английский. Движок i18n в index.html подменяет текст по совпадению ключа.
   Нет ключа — на сайте остаётся русский. Правьте свободно: сборки нет, файл статичный. */
window.EN = {
  '@title': `Blagoveshchensk: what to see, trips and a visit to Heihe — Amur Atlas guide`,
  '@desc': `A local's guide to Blagoveshchensk: 23 map points, a trip planner with a budget, how to cross into China's Heihe visa-free, the cable car, seasons and prices. Verified facts, July 2026.`,

  /* загрузчик + шапка */
  'Благовещенск': `Blagoveshchensk`,
  'Амур Атлас': `Amur Atlas`,
  'Зачем ехать': `Why go`,
  'Карта': `Map`,
  'События': `Events`,
  'Как доехать': `Getting there`,
  'Хэйхэ': `Heihe`,
  'Канатка': `Cable car`,
  'Маршрут': `Planner`,
  'История': `History`,
  'Любопытное': `Curious`,
  'Собрать маршрут': `Plan a trip`,

  /* hero */
  'Авторский гид · ИИщенко LAB': `An indie guide · Iishchenko LAB`,
  'Город на Амуре,<br>лицом к <span class="g">Китаю</span>': `A city on the Amur,<br>facing <span class="g">China</span>`,
  'Благовещенск — 750 метров воды до китайского Хэйхэ, купеческий «Амурский Чикаго», кухня двух стран, космодром Восточный и городское кладбище динозавров. Соберём маршрут под ваши интересы, сезон и бюджет.': `Blagoveshchensk sits just 750 metres of water from China's Heihe: a merchant-era "Amur Chicago", the cuisine of two countries, the Vostochny Cosmodrome, and a dinosaur graveyard right inside town. Let's build a trip around your interests, season and budget.`,
  'Собрать маршрут <span>→</span>': `Plan a trip <span>→</span>`,
  'Открыть карту': `Open the map`,
  '<b>23</b> точки на карте': `<b>23</b> points on the map`,
  '<b>4</b> эпохи истории': `<b>4</b> eras of history`,
  '<b>2</b> страны на тарелке': `<b>2</b> countries on a plate`,
  'RU ↔ CN<span>Амур · граница</span>': `RU ↔ CN<span>Amur · border</span>`,
  '<span class="dot"></span>Арка, Амур — и Хэйхэ за рекой': `<span class="dot"></span>The arch, the Amur — and Heihe beyond`,
  'воды до китайского Хэйхэ': `of water to China's Heihe`,
  'год основания города': `the year the city was founded`,
  'до космодрома Восточный': `to the Vostochny Cosmodrome`,
  'лет динозаврам под городом': `years — the dinosaurs beneath the city`,

  /* eyebrows секций */
  '01 — зачем ехать': `01 — why go`,
  '02 — интерактивная карта': `02 — interactive map`,
  '03 — что сейчас': `03 — what's on`,
  '04 — практика поездки': `04 — trip basics`,
  '05 — две страны за один день': `05 — two countries in a day`,
  '06 — скоро': `06 — coming soon`,
  '07 — конструктор маршрута': `07 — trip planner`,
  '08 — история': `08 — history`,
  '09 — гастрономия': `09 — food`,
  '10 — любопытное': `10 — curious facts`,
  '11 — вопросы': `11 — questions`,
  '12 — прогулка': `12 — a walk`,
  '13 — галерея': `13 — gallery`,

  /* заголовки и лиды секций */
  'Четыре разных Благовещенска<br>в одной <em>поездке</em>': `Four different Blagoveshchensks<br>in a single <em>trip</em>`,
  'За несколько дней — пройти по набережной лицом к китайскому мегаполису, застать купеческий «Амурский Чикаго», потрогать кости динозавров и увидеть, откуда стартуют ракеты.': `In a few days you can walk the embankment facing a Chinese metropolis, catch the merchant-era "Amur Chicago", touch dinosaur bones and see where the rockets launch.`,
  'Двадцать три <em>точки силы</em>': `Twenty-three <em>points of interest</em>`,
  'Кликайте на маркеры — описание и фото. Фильтруйте по категориям, чтобы спланировать день.': `Click a marker for a description and photo. Filter by category to plan your day.`,
  'События <em>прямо сейчас</em>': `Events <em>on right now</em>`,
  'Как добраться, когда ехать<br>и <em>сколько это стоит</em>': `How to get here, when to go<br>and <em>what it costs</em>`,
  'Благовещенск — 5 595 км от Москвы и шесть часовых поясов на восток. Разбираемся, чем сюда добираются, какой сезон под какие впечатления и на какие суммы ориентироваться.': `Blagoveshchensk is 5,595 km east of Moscow and six time zones away. Here's how people get here, which season fits which mood, and the sums to plan around.`,
  'Утром Россия,<br>днём <em>Китай</em>': `Russia in the morning,<br><em>China</em> by noon`,
  'Хэйхэ виден с набережной — 750 метров воды. Визы не нужно, хватает загранпаспорта: доехать до соседней страны отсюда проще и дешевле, чем до соседнего областного центра. Считаем, во что обойдётся.': `Heihe is right there from the embankment — 750 metres of water. No visa needed, just a passport: reaching the neighbouring country is easier and cheaper than the next region over. Let's price it out.`,
  'Первая в мире канатка<br><em>между двумя странами</em>': `The world's first cable car<br><em>between two countries</em>`,
  'Через Амур тянут канатную дорогу из России в Китай — такого нет больше нигде. Вместо парома и автобуса с формальностями — кабина и несколько минут над пограничной рекой. Стройку начали в 2019 году, сейчас она на финишной прямой.': `A cable car is being strung across the Amur from Russia to China — the only one of its kind anywhere. Instead of a ferry or a bus with formalities, a cabin and a few minutes above the border river. Construction began in 2019 and is now in its final stretch.`,
  'Соберём <em>персональный</em> маршрут': `Let's build your <em>personal</em> route`,
  'Алгоритм учитывает состав группы, сезон, интересы и бюджет — раскладывает активности по дням и прозрачно считает стоимость.': `The planner factors in your group, season, interests and budget — it spreads activities across days and prices everything transparently.`,
  'Четыре эпохи <em>на берегу Амура</em>': `Four eras <em>on the bank of the Amur</em>`,
  'Албазинский острог XVII века, рождение города при Муравьёве-Амурском, купеческий «Амурский Чикаго» и приграничный город XX–XXI веков — от погранзоны до моста и канатки в Китай.': `The 17th-century Albazin fort, the city's birth under Muravyov-Amursky, the merchant-era "Amur Chicago", and the 20th–21st-century border city — from a closed frontier to a bridge and a cable car into China.`,
  'Кухня <em>двух стран</em> на одном столе': `The cuisine of <em>two countries</em> on one table`,
  'Дунбэйская кухня соседнего Хэйхэ давно стала городской повседневностью, а рядом — амурская речная рыба, соя «соевой столицы» России, таёжные дикоросы и наследие казачества.': `The Dongbei cooking of neighbouring Heihe has long been everyday fare here — alongside Amur river fish, soy from Russia's "soy capital", wild taiga harvests and a Cossack heritage.`,
  'Неожиданный <em>Благовещенск</em>': `The <em>Blagoveshchensk</em> you don't expect`,
  'Факты, курьёзы и городские байки, которые превращают поездку в историю — из впечатлений тех, кто уже съездил на границу двух миров.': `Facts, oddities and city lore that turn a trip into a story — from those who've already been to this border between two worlds.`,
  'Что спрашивают <em>перед поездкой</em>': `What people ask <em>before the trip</em>`,
  'Короткие ответы на то, что обычно выясняют в первую очередь. Подробности — в блоках выше.': `Quick answers to the things people check first. Details are in the sections above.`,
  'Пройдёмся по <em>набережной</em>': `Let's walk the <em>embankment</em>`,
  'Пять шагов вдоль Амура — от Триумфальной арки до поющего фонтана. Листайте: карта идёт следом за вами.': `Five stops along the Amur — from the Triumphal Arch to the singing fountain. Scroll, and the map follows you.`,
  'Благовещенск <em>в кадре</em>': `Blagoveshchensk <em>in frame</em>`,
  'Набережная лицом к Китаю, Триумфальная арка, мост через Амур, космос и динозавры.': `The embankment facing China, the Triumphal Arch, the bridge across the Amur, space and dinosaurs.`,

  /* футер */
  'Готовы <em>увидеть</em> Благовещенск?': `Ready to <em>see</em> Blagoveshchensk?`,
  'К конструктору маршрута →': `To the trip planner →`,
  'Сайт создан жителем Благовещенска по собственной инициативе': `Made by a Blagoveshchensk local, on personal initiative`,
  'v2.0 · Амур Атлас · Благовещенск': `v2.0 · Amur Atlas · Blagoveshchensk`,

  /* единицы у счётчиков */
  'м': `m`, 'км': `km`, 'млн': `M`,

  /* WHY — bento */
  'Амур и граница': `The Amur and the border`,
  'Набережная, Триумфальная арка, памятник Муравьёву-Амурскому, первый автомост Россия–Китай и первая в мире трансграничная канатка в Хэйхэ.': `The embankment, the Triumphal Arch, the Muravyov-Amursky monument, the first Russia–China road bridge and the world's first cross-border cable car to Heihe.`,
  'воды до Китая — города стоят «глаза в глаза»': `of water to China — the cities stand eye to eye`,
  'Купеческий след': `A merchant past`,
  '«Амурский Чикаго»: золотая лихорадка, каменные особняки, пожарная каланча и три века казачества.': `The "Amur Chicago": a gold rush, stone mansions, a fire-watch tower and three centuries of Cossacks.`,
  'Кухня двух стран': `Cuisine of two countries`,
  'Дунбэйская кухня Хэйхэ, амурская речная рыба и уха, соя и тофу «соевой столицы», таёжные дикоросы и мёд, папоротник по-корейски.': `Heihe's Dongbei cooking, Amur river fish and fish soup, soy and tofu from the "soy capital", wild taiga harvests and honey, Korean-style fern.`,
  'Космос и динозавры': `Space and dinosaurs`,
  'Городское «кладбище динозавров» и старты ракет в 180 км — прошлое и будущее Приамурья рядом.': `A city dinosaur graveyard and rocket launches 180 km away — the Amur region's past and future side by side.`,

  /* карта — фильтры и панель */
  'Все 23': `All 23`,
  '<span class="dot" style="background:var(--c-nat)"></span>Природа': `<span class="dot" style="background:var(--c-nat)"></span>Nature`,
  '<span class="dot" style="background:var(--c-sea)"></span>Река': `<span class="dot" style="background:var(--c-sea)"></span>River`,
  '<span class="dot" style="background:var(--c-his)"></span>История': `<span class="dot" style="background:var(--c-his)"></span>History`,
  '<span class="dot" style="background:var(--c-gas)"></span>Гастро': `<span class="dot" style="background:var(--c-gas)"></span>Food`,
  '<span class="dot" style="background:var(--c-spa)"></span>Отдых': `<span class="dot" style="background:var(--c-spa)"></span>Leisure`,
  '<span class="dot" style="background:var(--c-city)"></span>Город': `<span class="dot" style="background:var(--c-city)"></span>City`,
  'Точки по категориям': `Points by category`,
  'Из чего складываются 23 места': `What the 23 spots break down into`,

  /* события — вкладки */
  'афиша сезона': `this season's lineup`,
  'Все': `All`, 'Фестивали': `Festivals`, 'Выставки': `Exhibitions`, 'Гастро': `Food`,
  'Природа': `Nature`, 'Спектакли': `Theatre`, 'Ярмарки': `Markets`,

  /* практика поездки — как добраться */
  'Как добраться': `Getting there`,
  'Три дороги в город на Амуре': `Three roads into the city on the Amur`,
  'Самолётом': `By plane`,
  'Прямые рейсы из Москвы — 5 595 км, от 7 ч 25 мин. Аэропорт Игнатьево (BQS) в 15 км от центра: городской автобус №8, пригородные 503 и 510 до автовокзала, такси — 20–30 минут. Разница с Москвой +6 часов, к перелёту добавьте день на акклиматизацию.': `Direct flights from Moscow — 5,595 km, from 7 h 25 min. Ignatyevo airport (BQS) is 15 km from the centre: city bus No. 8, suburban buses 503 and 510 to the coach station, a taxi 20–30 minutes. Moscow is 6 hours behind, so add a day to adjust after the flight.`,
  'Поездом': `By train`,
  'Транссиб проходит мимо города: ближайший узел — Белогорск, около 110 км. Оттуда до Благовещенска автобус или пригородный поезд, 2–2,5 часа. Вариант для тех, кто едет за дорогой, а не за скоростью.': `The Trans-Siberian bypasses the city: the nearest hub is Belogorsk, about 110 km away. From there a bus or a local train to Blagoveshchensk, 2–2.5 hours. For those travelling for the journey, not the speed.`,
  'Из Китая, через Амур': `From China, across the Amur`,
  'Автомост Россия–Китай у Кани-Кургана с пассажирскими автобусами, летом — паром, зимой — понтонная переправа. Первая в мире трансграничная канатка Благовещенск–Хэйхэ: запуск намечен на конец 2026 года, 6–8 минут над границей.': `The Russia–China road bridge at Kani-Kurgan with passenger buses; a ferry in summer, a pontoon crossing in winter. And the world's first cross-border cable car, Blagoveshchensk–Heihe, due to open in late 2026 — 6–8 minutes over the border.`,
  'Сколько стоит': `What it costs`,
  'Ориентиры на одного человека': `Ballpark figures, per person`,
  'Перелёт Москва ⇄ Благовещенск': `Moscow ⇄ Blagoveshchensk flight`,
  'Субсидированный тариф, в одну сторону': `Subsidised fare, one way`,
  'Обед в китайском кафе': `Lunch at a Chinese café`,
  'Ужин с амурской рыбой': `Dinner with Amur fish`,
  'Музей, вход': `Museum admission`,
  'День в Хэйхэ (нужен загран)': `A day in Heihe (passport needed)`,
  'Экскурсия на космодром Восточный': `Vostochny Cosmodrome tour`,
  'Субсидированный тариф — для молодёжи, пенсионеров, многодетных семей и жителей Дальнего Востока; продажа на год открывается в декабре и билеты быстро разбирают. Цена перелёта сильно зависит от даты и глубины покупки. Проживание и суточные посчитает конструктор маршрута ниже — под ваш бюджет, сезон и число ночей.': `The subsidised fare is for young people, pensioners, large families and residents of the Far East; the year's tickets go on sale in December and sell out fast. Airfare depends heavily on the date and how far ahead you book. Lodging and daily costs are worked out by the trip planner below — around your budget, season and number of nights.`,

  /* сезоны */
  'Декабрь — февраль': `December – February`,
  'Зима': `Winter`,
  'Амур встаёт, и по льду открывают понтонную переправу в Китай. Каток на набережной, огни Хэйхэ напротив, пустые музеи. Морозы сухие, но серьёзные — экипировка нужна честная.': `The Amur freezes and a pontoon crossing to China opens over the ice. A rink on the embankment, Heihe's lights across the river, empty museums. The cold is dry but serious — bring proper gear.`,
  'для смелых': `for the bold`,
  'Март — май': `March – May`,
  'Весна': `Spring`,
  'Ледоход на Амуре': `Ice drift on the Amur`,
  'Главное зрелище сезона — ледоход, обычно в конце апреля (в 2026-м лёд между Благовещенском и Хэйхэ тронулся 19 апреля, раньше срока). Город оживает, туристов ещё мало, цены спокойные.': `The season's big spectacle is the ice drift, usually in late April (in 2026 the ice between Blagoveshchensk and Heihe broke on 19 April, ahead of schedule). The city wakes up, tourists are still few, prices are calm.`,
  'ледоход': `ice drift`,
  'Июнь — август': `June – August`,
  'Лето': `Summer`,
  'Лето<span class="sea-now">сейчас</span>': `Summer<span class="sea-now">now</span>`,
  'Набережная, теплоходы, фонтаны. Краснокнижные лотосы Комарова у Ивановки цветут с середины июля, пик — начало августа. Самый людный сезон и самый дождливый: июль — месяц осадков.': `The embankment, riverboats, fountains. The protected Komarov lotuses near Ivanovka bloom from mid-July, peaking in early August. The busiest season, and the wettest: July is the rainy month.`,
  'лучшее время': `best time`,
  'Сентябрь — ноябрь': `September – November`,
  'Осень': `Autumn`,
  '«Амурская осень»': `"Amur Autumn"`,
  'В сентябре в городе кинофестиваль: премьеры, театр, звёзды на набережной. Золотая тайга вокруг, комфортное тепло в начале сезона и заметно меньше людей, чем летом.': `In September the city hosts a film festival: premieres, theatre, stars on the embankment. Golden taiga all around, comfortable warmth early in the season, and far fewer people than in summer.`,
  'фестивали': `festivals`,

  /* Хэйхэ — виза, способы */
  'Виза не нужна — но поездка не бесплатная': `No visa needed — but the trip isn't free`,
  'С 15 сентября 2025 года россияне въезжают в Китай без визы на срок до 30 дней; в мае 2026-го режим продлили до 31 декабря 2027 года. Нужен только загранпаспорт, действующий ещё минимум 6 месяцев — ни приглашения, ни брони отеля, ни справок. Бесплатна именно виза: за саму переправу через Амур платить придётся, и это основная статья расходов.': `Since 15 September 2025 Russians enter China visa-free for up to 30 days; in May 2026 the arrangement was extended to 31 December 2027. All you need is a passport valid for at least 6 more months — no invitation, hotel booking or paperwork. It's the visa that's free: the crossing over the Amur itself is paid, and that's the main expense.`,
  'Теплоходом': `By riverboat`,
  'навигация · май – октябрь': `season · May – October`,
  'Классика: 10–15 минут по воде плюс формальности. Отправления из Благовещенска в 10:00, 12:00, 14:00 и 16:00 по амурскому времени. Туда 3 780 ₽, обратно 2 520 ₽. В межсезонье, когда лёд ещё не встал, ходят суда на воздушной подушке — дороже.': `The classic option: 10–15 minutes on the water plus formalities. Departures from Blagoveshchensk at 10:00, 12:00, 14:00 and 16:00 Amur time. 3,780 ₽ over, 2,520 ₽ back. In the off-season, before the ice sets, hovercraft run — pricier.`,
  'Автобусом по мосту': `By bus over the bridge`,
  'круглый год': `year-round`,
  'Через первый автомост Россия–Китай. Первый рейс от автовокзала «Амурассо» в 07:30, в Хэйхэ в 09:50; последний из Благовещенска — в 14:10. Около 2 650 ₽ в одну сторону, в пути ~2 ч 20 мин вместе с границей. Зимой работает и понтонная переправа.': `Over the first Russia–China road bridge. First departure from the "Amurasso" coach station at 07:30, in Heihe by 09:50; last one out of Blagoveshchensk at 14:10. About 2,650 ₽ one way, ~2 h 20 min including the border. In winter a pontoon crossing runs too.`,
  'Канатной дорогой': `By cable car`,
  'запуск — конец 2026': `opening — late 2026`,
  'Первая в мире трансграничная канатка через государственную границу. Кабины до 110 человек, 6–8 минут над Амуром. Канат через реку натянули в июле 2026-го, запуск намечен на конец года — цены пока не объявлены.': `The world's first cross-border cable car over a state frontier. Cabins hold up to 110 people, 6–8 minutes above the Amur. The cable was strung across the river in July 2026; opening is set for the end of the year — fares not yet announced.`,
  'Экономика поездки': `The cost of a trip`,
  'Прикиньте бюджет на свою компанию': `Estimate the budget for your group`,
  'Как добираетесь': `How you travel`,
  'Теплоход': `Riverboat`,
  'май – октябрь': `May – October`,
  'Автобус': `Bus`,
  'Сколько человек': `How many people`,
  'Ночёвок в Хэйхэ': `Nights in Heihe`,
  'Уровень гостиницы': `Hotel level`,
  'Бюджет': `Budget`,
  'от 1 285 ₽': `from 1,285 ₽`,
  '3 звезды': `3 stars`,
  'Центр': `Central`,
  'от 3 870 ₽': `from 3,870 ₽`,
  'На еду и покупки, в день': `Food and shopping, per day`,
  'Как проходит день': `How the day goes`,
  'Хэйхэ вблизи': `Heihe up close`,
  'Отели и торговые улицы — в паре минут от причала': `Hotels and shopping streets — minutes from the pier`,
  'Зелёный город': `A green city`,
  'Велодорожки и парки на улицах Хэйхэ': `Bike lanes and parks along Heihe's streets`,
  'Время назад на час': `An hour back in time`,
  'Хэйхэ живёт по пекинскому времени, Благовещенск — по амурскому. Пересекая Амур, вы отматываете час назад, а возвращаясь — теряете. Расписание переправ — по амурскому.': `Heihe runs on Beijing time, Blagoveshchensk on Amur time. Crossing the river you gain an hour; coming back you lose it. Crossing timetables are in Amur time.`,
  'Торгуйтесь': `Haggle`,
  'На рынках и в торговых центрах цена начальная, а не окончательная. Обычная практика — сбить 10–30%. Без торга вы просто переплатите.': `In markets and malls the price is a starting point, not a final one. Knocking off 10–30% is normal. Without haggling you simply overpay.`,
  'Обратно дольше': `The way back is slower`,
  'Туда границу проходят быстро, обратно — медленнее: досмотр покупок. Закладывайте запас и не берите последний рейс впритык.': `The border is quick on the way in, slower on the way out — they inspect your shopping. Leave a buffer and don't cut it close with the last departure.`,
  'Зачем едут': `Why people go`,
  'Рынки и техника, дунбэйская кухня, спа и массаж, набережная с видом на Россию, парк водно-болотных угодий. Отдельная история — стоматология и косметология «под ключ».': `Markets and electronics, Dongbei food, spas and massage, a promenade looking back at Russia, a wetlands park. And a category of its own — all-in-one dentistry and cosmetic procedures.`,
  'Цены — ориентиры на июль 2026 по данным перевозчиков, сервисов бронирования и городских СМИ Приамурья; тарифы и расписание меняются, перед поездкой сверяйтесь с перевозчиком. Расчёт не включает страховку и обмен валюты. Обратные рейсы уточняйте отдельно — их расписание корректируют по погоде и загрузке.': `Prices are ballpark figures for July 2026 from carriers, booking services and Amur-region local media; fares and schedules change, so check with the carrier before you go. The estimate excludes insurance and currency exchange. Confirm return departures separately — their timing is adjusted for weather and demand.`,

  /* канатка */
  'Готовность около 90% · трос через Амур протянут 2 июля 2026': `About 90% complete · the cable was strung across the Amur on 2 July 2026`,
  'дней до декабря 2026 — месяца, когда объект обещают довести до готовности к эксплуатации<br><em>ориентир по Хэйлунцзянскому ТВ (июль 2026); сроки уже переносили — перед поездкой перепроверьте</em>': `days until December 2026 — the month the project is promised to be ready for operation<br><em>per Heilongjiang TV (July 2026); the date has slipped before — double-check before your trip</em>`,
  'Терминал на «Золотой миле» и кабина над Амуром': `The terminal on the "Golden Mile" and a cabin above the Amur`,
  'Проектная визуализация: терминальная станция по проекту бюро UNStudio, победителя международного конкурса': `Concept render: the terminal station designed by UNStudio, winner of the international competition`,
  'длина трассы над Амуром и государственной границей': `length of the line above the Amur and the state border`,
  'в пути между двумя странами': `travel time between the two countries`,
  'вместимость каждой из двух кабин': `capacity of each of the two cabins`,
  'пропускная способность в одну сторону': `one-way capacity per hour`,
  'Что будет в терминале': `What the terminal will hold`,
  'Четырёхэтажное здание на набережной: пограничный и таможенный контроль, магазины duty free, торговая галерея и ресторан с видом на Амур. Работать планируют ежедневно с 07:00 до 23:00. Стоимость проекта — около 10 млрд рублей.': `A four-storey building on the embankment: border and customs control, duty-free shops, a retail gallery and a restaurant overlooking the Amur. Planned hours are 07:00 to 23:00 daily. The project costs around 10 billion roubles.`,
  'июль 2019': `July 2019`,
  'Начало строительства на российском берегу': `Construction begins on the Russian bank`,
  'Смонтирована опора высотой 64 метра, поднят корпус терминала': `A 64-metre support tower is erected, the terminal shell goes up`,
  'январь 2026': `January 2026`,
  'Китайская часть готова на 97%, идёт монтаж оборудования': `The Chinese side is 97% done, equipment is being installed`,
  '2 июля 2026': `2 July 2026`,
  'Тросы протянуты через Амур — мы сейчас здесь': `The cables are strung across the Amur — we're here now`,
  'декабрь 2026': `December 2026`,
  'Пусконаладка и готовность к эксплуатации': `Commissioning and readiness for operation`,
  'О сроках честно: их уже переносили. Сначала запуск обещали на весну 2026-го, потом говорили о тестовом пуске в июле. По самым свежим данным — Хэйлунцзянское телевидение, 5 июля 2026 года — пусконаладочные работы пройдут в конце года, а к эксплуатации объект будет готов в декабре. Так что если планируете проехать над Амуром — рассчитывайте на зиму, а не на осень.<br><br>Цену билета официально не объявляли. В публикациях называют ориентир около 3 000 ₽ за поездку туда и обратно, но это оценка, а не тариф.': `Honestly about the timing: it has slipped before. First the opening was promised for spring 2026, then a test run in July. Per the latest — Heilongjiang TV, 5 July 2026 — commissioning will happen at the end of the year, and the facility will be ready for operation in December. So if you're planning to ride over the Amur, count on winter, not autumn.<br><br>The fare hasn't been announced officially. Reports cite a ballpark of about 3,000 ₽ for a round trip, but that's an estimate, not a tariff.`,
  'Пока канатка не открылась, в Китай ходят теплоходы и автобусы по мосту — как добраться и во что обойдётся, посчитано в блоке <a href="#heihe" style="color:#e79fc9;text-decoration:underline;text-underline-offset:3px">«Две страны за один день»</a> выше.': `Until the cable car opens, riverboats and buses over the bridge run to China — how to get there and what it costs is worked out in the <a href="#heihe" style="color:#e79fc9;text-decoration:underline;text-underline-offset:3px">"Two countries in a day"</a> block above.`,

  /* планировщик — форма */
  'Состав': `Group`,
  'Соло': `Solo`,
  'Свобода маршрута': `A route of your own`,
  'Пара': `Couple`,
  'Отдых вдвоём': `A trip for two`,
  'Друзья': `Friends`,
  'Компания': `A group`,
  'Семья': `Family`,
  'С детьми': `With kids`,
  'Сезон': `Season`,
  'Лёд на Амуре': `Ice on the Amur`,
  'Ледоход, тепло': `Ice drift, warming up`,
  'Амур, лотосы': `The Amur, lotuses`,
  'Сколько дней': `How many days`,
  'Что интересно': `What interests you`,
  'Река, Амур': `River, the Amur`,
  'Гастрономия': `Food`,
  'Актив': `Active`,
  'Отдых': `Leisure`,
  'Китай, казачество': `China, Cossacks`,
  'Рыбалка': `Fishing`,
  'Город, музеи': `City, museums`,
  'Бюджет на одного в день': `Budget per person, per day`,
  'Собрать маршрут →': `Build the route →`,
  'Здесь появится маршрут': `Your route appears here`,
  'Заполните анкету слева — алгоритм подберёт активности по дням, построит таймлайн и посчитает бюджет с разбивкой.': `Fill in the form on the left — the planner will pick activities day by day, build a timeline and break down the budget.`,

  /* история — 4 эпохи */
  'Албазин — первый форпост на Амуре': `Albazin — the first outpost on the Amur`,
  'В 1651 году отряд Ерофея Хабарова занял городок даурского князя Албазы — так возник Албазинский острог, первое русское поселение на Амуре. В 1685–1686 годах горстка казаков дважды держала оборону против многократно превосходящих цинских войск.': `In 1651 Yerofey Khabarov's party took the town of the Daur prince Albaza — and so the Albazin fort arose, the first Russian settlement on the Amur. In 1685–1686 a handful of Cossacks twice held out against vastly larger Qing forces.`,
  '«Из нескольких сотен защитников второй осады Албазина в живых осталось около двадцати казаков — но крепость не сдалась.»': `"Of the several hundred defenders of Albazin's second siege, some twenty Cossacks survived — but the fort did not fall."`,
  'Рождение города и возвращение Амура': `The city's birth and the return of the Amur`,
  'На слиянии Зеи и Амура основан Усть-Зейский пост. Муравьёв-Амурский подписал в 1858 году Айгунский договор, вернувший Приамурье России. В том же году пост стал городом Благовещенском — в честь «благой вести» о возвращении земель.': `At the confluence of the Zeya and the Amur the Ust-Zeysky post was founded. In 1858 Muravyov-Amursky signed the Treaty of Aigun, returning the Amur region to Russia. That same year the post became the city of Blagoveshchensk — named for the "good news" of the lands' return.`,
  '«Город назвали Благовещенском, потому что возвращение Амура России сочли настоящей „благой вестью“.»': `"The city was named Blagoveshchensk because the Amur's return to Russia was seen as truly 'good news' (blagaya vest')."`,
  'конец XIX – нач. XX в.': `late 19th – early 20th c.`,
  '«Амурский Чикаго» — золото и купцы': `The "Amur Chicago" — gold and merchants`,
  'Золотая лихорадка на приисках Зеи и беспошлинная торговля с Китаем сделали Благовещенск богатейшим городом востока. Купеческие капиталы подняли особняки, банки, электростанцию и водопровод раньше многих губернских столиц.': `A gold rush on the Zeya diggings and duty-free trade with China made Blagoveshchensk the richest city in the east. Merchant capital raised mansions, banks, a power station and running water earlier than in many provincial capitals.`,
  '«На рубеже веков Благовещенск по числу купеческих капиталов соперничал со столичными городами.»': `"At the turn of the century Blagoveshchensk rivalled the capital cities in the number of merchant fortunes."`,
  'XX – XXI в.': `20th – 21st c.`,
  'Приграничный город — от погранзоны до космоса': `A border city — from a closed zone to space`,
  'В советские годы Благовещенск был закрытой погранзоной. Сегодня это главные «ворота» в Китай: автомост через Амур (2022) и первая в мире трансграничная канатка в Хэйхэ. А в 180 км началась новая эпоха — космодром Восточный.': `In the Soviet era Blagoveshchensk was a closed border zone. Today it's the main "gateway" to China: a road bridge over the Amur (2022) and the world's first cross-border cable car to Heihe. And 180 km away a new era began — the Vostochny Cosmodrome.`,
  '«Благовещенск и Хэйхэ разделяет всего около 750 метров воды — единственная в мире пара городов-соседей двух стран, стоящих так близко.»': `"Just about 750 metres of water separate Blagoveshchensk and Heihe — the world's only pair of neighbouring cities of two countries standing so close."`,

  /* слайдер до/после */
  'Та же арка — сто двадцать лет спустя': `The same arch — a hundred and twenty years apart`,
  'Потяните ползунок. Слева — Триумфальная арка на снимке 1904 года, справа — она же в наши дни. Оригинал 1891 года не пережил XX век: нынешнюю арку восстановили в 2005-м по старым фотографиям.': `Drag the slider. On the left, the Triumphal Arch in a photo from 1904; on the right, the same arch today. The 1891 original did not survive the 20th century: the present arch was rebuilt in 2005 from old photographs.`,
  'наши дни': `today`,
  'Слева: фото 1904 года из книги Элима Демидова, общественное достояние. Справа: фото 2013 года, Sharon Hahn Darlin, CC BY 2.0 — обе с Wikimedia Commons. Нынешняя арка воссоздана в 2005 году по фотографиям оригинала.': `Left: a 1904 photo from Elim Demidov's book, public domain. Right: a 2013 photo, Sharon Hahn Darlin, CC BY 2.0 — both from Wikimedia Commons. The present arch was recreated in 2005 from photographs of the original.`,

  /* кухня */
  'Амурский сазан и уха': `Amur carp and fish soup`,
  'Речная рыба Амура — сазан, верхогляд, косатка-скрипун — на гриле или в наваристой ухе. Порция ~500–900 ₽.': `Amur river fish — carp, skygazer, catfish — grilled or in a rich fish soup. A portion is ~500–900 ₽.`,
  'Калуга и амурский осётр': `Kaluga and Amur sturgeon`,
  'Легендарные гиганты Амура. Дикий вылов запрещён — к столу подают аквакультурную рыбу и икру (от 1 500 ₽).': `The Amur's legendary giants. Wild catch is banned — farmed fish and caviar are served instead (from 1,500 ₽).`,
  'Го-бао-жоу по-хэйхэйски': `Guo bao rou, Heihe style`,
  'Свинина в кисло-сладком кляре — визитка дунбэйской кухни. Сотни китайских кафе, чек 400–800 ₽.': `Sweet-and-sour battered pork — the signature of Dongbei cooking. Hundreds of Chinese cafés, a bill of 400–800 ₽.`,
  'Папоротник-орляк': `Bracken fern`,
  'Таёжный дикорос, маринованный или обжаренный с мясом «по-корейски». Хрустящая закуска.': `A wild taiga plant, pickled or stir-fried with meat "Korean style". A crunchy starter.`,
  'Соя и тофу': `Soy and tofu`,
  'Амурская область — «соевая столица» России. Соевое молоко, тофу, окара, соусы — специалитет и сувенир.': `The Amur region is Russia's "soy capital". Soy milk, tofu, okara, sauces — both a specialty and a souvenir.`,
  'Амурский таёжный мёд': `Amur taiga honey`,
  'Липовый и разнотравный мёд Приамурья — популярный гостинец с городских рынков и ярмарок.': `Linden and wildflower honey from the Amur region — a favourite gift from the city's markets and fairs.`,
  'Дикоросы: лимонник, брусника': `Wild harvest: schisandra, lingonberry`,
  'Морсы, настойки, варенья из таёжных ягод. Лимонник — местный природный «энергетик».': `Fruit drinks, tinctures and jams from taiga berries. Schisandra is the local natural "energy drink".`,
  'Казачий рыбник': `Cossack fish pie`,
  'Закрытый рыбный пирог амурского казачества с речной рыбой. Сытно и по-домашнему.': `A sealed river-fish pie of the Amur Cossacks. Hearty and homemade.`,

  /* факты */
  '750 метров — и ты в другом мире': `750 metres — and you're in another world`,
  'С набережной видно, как живёт китайский Хэйхэ. <b>Единственная в мире пара городов двух стран</b>, стоящих так близко: свои язык, кухня, деньги и уклад — через одну реку.': `From the embankment you can watch Chinese Heihe go about its day. <b>The world's only pair of cities of two countries</b> standing this close: their own language, food, money and way of life — across a single river.`,
  'Почти все машины — «праворульки»': `Nearly every car is right-hand drive`,
  'Около <b>90% автомобилей праворульные</b>, и таксист сидит справа. Дальневосточная привычка, к которой приезжие привыкают буквально за день.': `About <b>90% of cars are right-hand drive</b>, and the taxi driver sits on the right. A Far Eastern habit that visitors get used to within a day.`,
  'Памятник Челноку': `A monument to the shuttle trader`,
  'В 90-е «кирпичи» — люди-перевозчики — таскали через Амур <b>больше 30 тонн товара в день</b>. Челночный бизнес держал город на плаву, когда экономика стояла. Ему поставили памятник.': `In the 1990s the "bricks" — human couriers — hauled <b>over 30 tonnes of goods a day</b> across the Amur. Shuttle trading kept the city afloat when the economy stalled. It got its own monument.`,
  'Юань всё перевернул': `The yuan flipped everything`,
  'Когда юань стоил 3–5 ₽, русские ездили в Хэйхэ за всем подряд. Теперь юань 12–13 ₽ — и <b>уже китайцы едут скупать в Благовещенск</b>.': `When the yuan cost 3–5 ₽, Russians went to Heihe for everything. Now the yuan is 12–13 ₽ — and <b>it's the Chinese who come to shop in Blagoveshchensk</b>.`,
  'Пёс Дружок с набережной': `Druzhok, the embankment dog`,
  'В наводнение 2013-го Амур поднялся до рекордных 822 см (больше 8 метров) и затопил 126 населённых пунктов области. Пёс несколько дней ждал хозяев на крыльце затопленного дома — теперь <b>бронзовый Дружок «охраняет весь город»</b>.': `In the 2013 flood the Amur rose to a record 822 cm (over 8 metres) and swamped 126 settlements in the region. A dog waited days for his owners on the porch of a flooded house — now <b>a bronze Druzhok "guards the whole city"</b>.`,
  'Арку построили за полгода': `The arch went up in half a year`,
  'Триумфальную арку возвели к приезду цесаревича Николая. Такие же ставили в Хабаровске и Владивостоке, но <b>благовещенская — самая большая</b>.': `The Triumphal Arch was raised for the visit of Tsarevich Nicholas. Similar ones went up in Khabarovsk and Vladivostok, but <b>Blagoveshchensk's is the largest</b>.`,
  'Канатка из страны в страну': `A cable car from country to country`,
  'Первая в мире трансграничная канатная дорога через Амур. Кабины — <b>до 110 человек каждая</b>, и над рекой между двумя государствами всего несколько минут.': `The world's first cross-border cable car over the Amur. Cabins hold <b>up to 110 people each</b>, and it's just a few minutes over the river between two states.`,
  'Балалайка встречает пипу': `A balalaika meets a pipa`,
  'В парке Дружбы за китайской пагодой стоит советская панелька, а рядом — <b>памятник русской балалайке и китайской пипе</b>. Мир, дружба, музыка.': `In Friendship Park, behind a Chinese pagoda stands a Soviet apartment block, and beside it — <b>a monument to the Russian balalaika and the Chinese pipa</b>. Peace, friendship, music.`,
  'За здоровьем — в Китай': `To China for your health`,
  'В Хэйхэ летят со всей России за <b>стоматологией и бьюти-процедурами «под ключ»</b>: дешевле, с гарантией и всем спектром услуг в одном центре.': `People fly to Heihe from across Russia for <b>all-in-one dentistry and beauty treatments</b>: cheaper, guaranteed, and the full range of services in one centre.`,
  'Порция — минимум 400 грамм': `A portion is at least 400 grams`,
  'В китайских кафе блюда заказывают <b>на всех и ставят в центр стола</b>. Меньше 400 г не бывает — вдвоём осилить три блюда почти нереально.': `In Chinese cafés dishes are ordered <b>for everyone and placed in the middle of the table</b>. Nothing comes under 400 g — two people finishing three dishes is nearly impossible.`,
  'Когда на набережной стояли пушки': `When cannon stood on the embankment`,
  'В 1900-м, во время Боксёрского восстания в Китае, граница у города на пару месяцев стала <b>линией вооружённого противостояния</b>. Сегодня на том же берегу — прогулки и фонтаны.': `In 1900, during the Boxer Rebellion in China, the border by the city briefly became <b>a line of armed standoff</b> for a couple of months. Today that same bank has strolls and fountains.`,
  'Фонтан, по которому ходят': `A fountain you walk through`,
  'На площади Ленина — <b>крупнейший в Евразии пешеходный светомузыкальный фонтан</b>: почти 3 000 м² струй бьют прямо из мостовой. Днём в нём носятся дети, вечером — водно-световое шоу; сезон открывают 1 мая.': `On Lenin Square stands <b>Eurasia's largest walk-through light-and-music fountain</b>: nearly 3,000 m² of jets rise straight from the pavement. By day children dash through it; by night, a water-and-light show. The season opens on 1 May.`,
  'Солнце здесь — норма': `Sunshine is the norm here`,
  'По климатическим справочникам у Благовещенска <b>около 186 солнечных дней в году</b> — больше половины календаря. Июль выдаёт до 23 солнечных дней, а морозная зима — это почти всегда ясное небо.': `By climate references Blagoveshchensk has <b>about 186 sunny days a year</b> — more than half the calendar. July delivers up to 23 sunny days, and the frosty winter is almost always clear-skied.`,
  'Нейросеть-цензор в музее': `An AI censor in the museum`,
  'В музее спросили про тот конфликт у китайского DeepSeek — он <b>вежливо отказался отвечать</b>. ChatGPT рассказал всё. Один вопрос — разные страны, разные ответы.': `At the museum they asked China's DeepSeek about that conflict — it <b>politely declined to answer</b>. ChatGPT told all. One question, different countries, different answers.`,

  /* FAQ */
  'Нужна ли виза, чтобы съездить в Хэйхэ?': `Do I need a visa to visit Heihe?`,
  'Нет. С 15 сентября 2025 года россияне въезжают в Китай <b>без визы на срок до 30 дней</b>, в мае 2026-го режим продлили до конца 2027 года. Нужен только загранпаспорт, действующий ещё минимум 6 месяцев, — без приглашений, броней и справок. Сама переправа платная: теплоходом около 6 300 ₽ туда-обратно, автобусом по мосту около 5 300 ₽.': `No. Since 15 September 2025 Russians enter China <b>visa-free for up to 30 days</b>; in May 2026 this was extended to the end of 2027. You only need a passport valid for at least 6 more months — no invitations, bookings or paperwork. The crossing itself is paid: about 6,300 ₽ round trip by riverboat, about 5,300 ₽ by bus over the bridge.`,
  'Как добраться до Благовещенска из Москвы?': `How do I get to Blagoveshchensk from Moscow?`,
  'Прямым рейсом — 5 595 км, от 7 ч 25 мин. Билеты от ~10 000 ₽ в одну сторону при ранней покупке; для молодёжи, пенсионеров, многодетных и жителей Дальнего Востока есть субсидированный тариф 9 700 ₽. Поездом — до Белогорска на Транссибе (~110 км), дальше автобус или пригородный, 2–2,5 часа. Разница с Москвой +6 часов.': `By direct flight — 5,595 km, from 7 h 25 min. Tickets from ~10,000 ₽ one way if booked early; young people, pensioners, large families and Far East residents get a subsidised fare of 9,700 ₽. By train — to Belogorsk on the Trans-Siberian (~110 km), then a bus or local train, 2–2.5 hours. Moscow is 6 hours behind.`,
  'Когда лучше ехать в Благовещенск?': `When is the best time to visit Blagoveshchensk?`,
  'Универсальный ответ — <b>лето</b>: набережная, теплоходы, лотосы, +22…+28 °C. Но у каждого сезона свой козырь: в конце апреля — ледоход на Амуре, в сентябре — кинофестиваль «Амурская осень» и бархатное тепло, зимой — замёрзшая река, каток и огни Хэйхэ через лёд при −15…−27 °C.': `The safe answer is <b>summer</b>: the embankment, riverboats, lotuses, +22…+28 °C. But each season has its trump card: late April brings the ice drift on the Amur, September the "Amur Autumn" film festival and mellow warmth, winter a frozen river, a skating rink and Heihe's lights across the ice at −15…−27 °C.`,
  'Когда цветут лотосы и где их смотреть?': `When do the lotuses bloom, and where to see them?`,
  'С середины июля до середины августа, пик — начало августа. Ближайшее к городу место — озеро у села Ивановка, около часа на машине. Лотос Комарова — краснокнижный: рвать нельзя, фотографировать — сколько угодно.': `From mid-July to mid-August, peaking in early August. The closest spot to the city is a lake near the village of Ivanovka, about an hour by car. The Komarov lotus is protected: no picking, but photograph all you like.`,
  'Правда, что почти все машины — праворульные?': `Is it true that nearly all cars are right-hand drive?`,
  'Правда: около <b>90% автомобилей в городе с правым рулём</b>, японский автопром — дальневосточная классика. Таксист будет сидеть справа. Приезжие привыкают за день, а для местных это просто норма.': `True: about <b>90% of the city's cars are right-hand drive</b> — Japanese vehicles are a Far Eastern staple. Your taxi driver will sit on the right. Visitors adjust in a day; for locals it's just normal.`,
  'Сколько стоит день в Хэйхэ?': `How much does a day in Heihe cost?`,
  'Ориентир на одного: переправа 5 300–6 300 ₽ туда-обратно, обед в китайском кафе 400–800 ₽, покупки — по аппетиту (торговаться обязательно, сбивают 10–30%). Итого день «посмотреть и поесть» — примерно 8–10 тысяч ₽. Ночёвка добавит от 1 300 ₽ за номер.': `Ballpark per person: the crossing 5,300–6,300 ₽ round trip, lunch at a Chinese café 400–800 ₽, shopping to taste (haggling is a must — 10–30% off). A "see and eat" day comes to roughly 8,000–10,000 ₽. A night's stay adds from 1,300 ₽ per room.`,
  'Когда откроется канатная дорога в Китай?': `When will the cable car to China open?`,
  'По данным на июль 2026-го — <b>декабрь 2026</b>: тросы через Амур протянуты, готовность около 90%, пусконаладка в конце года. Сроки уже переносили, так что перед поездкой стоит перепроверить. Пока работают теплоход и автобус по мосту.': `As of July 2026 — <b>December 2026</b>: the cables are strung across the Amur, it's about 90% complete, with commissioning at year's end. The date has slipped before, so double-check before your trip. For now the riverboat and the bridge bus are running.`,
  'Чем платить в Хэйхэ?': `How do I pay in Heihe?`,
  'Российские карты Visa и Mastercard в Китае не работают. Берите <b>наличные юани</b> — обменять можно в банках Благовещенска. В туристических местах Хэйхэ, ориентированных на россиян, часто принимают и рубли, но курс там хуже. Основной способ оплаты у самих китайцев — Alipay и WeChat Pay.': `Russian Visa and Mastercard don't work in China. Bring <b>cash yuan</b> — you can exchange it at banks in Blagoveshchensk. In Heihe's Russia-facing tourist spots roubles are often accepted too, but the rate is worse. The Chinese themselves mostly pay by Alipay and WeChat Pay.`,

  /* сторителлинг по набережной */
  '01 · старт': `01 · start`,
  'Триумфальная арка': `The Triumphal Arch`,
  'Отсюда начинается парадный выход к Амуру. Двадцатиметровую арку с двуглавыми орлами поставили в 1891-м к визиту цесаревича Николая, воссоздали в 2005-м. За ней открывается река и китайский берег.': `The grand approach to the Amur starts here. The twenty-metre arch with double-headed eagles was raised in 1891 for Tsarevich Nicholas's visit and recreated in 2005. Beyond it open the river and the Chinese bank.`,
  '<svg viewBox="0 0 24 24"><path d="M12 5v14M6 13l6 6 6-6"></path></svg>листайте вниз — идём дальше': `<svg viewBox="0 0 24 24"><path d="M12 5v14M6 13l6 6 6-6"></path></svg>scroll down — let's go on`,
  'Памятник Муравьёву-Амурскому': `The Muravyov-Amursky monument`,
  'Основатель города и «собиратель» Приамурья стоит на набережной и смотрит на Амур с Китаем за ним. Именно он подписал Айгунский договор 1858 года, вернувший эти земли России.': `The city's founder and "gatherer" of the Amur region stands on the embankment, looking out at the Amur with China beyond. It was he who signed the 1858 Treaty of Aigun that returned these lands to Russia.`,
  'Лицом к Хэйхэ — 750 метров': `Facing Heihe — 750 metres`,
  'Здесь Амур сужается до 750 метров, и с парапета виден китайский Хэйхэ: высотки, набережная, вечерние огни. Единственная в мире пара городов двух стран, стоящих так близко, — глаза в глаза через реку.': `Here the Amur narrows to 750 metres, and from the parapet you can see Chinese Heihe: towers, a promenade, evening lights. The world's only pair of cities of two countries standing this close — eye to eye across the river.`,
  'Река': `River`,
  'Пёс Дружок': `Druzhok the dog`,
  'Бронзовый пёс на парапете — память о наводнении 2013 года, когда Амур поднялся выше 8 метров. Он несколько дней ждал хозяев на крыльце затопленного дома; теперь, по словам горожан, «охраняет весь город».': `A bronze dog on the parapet — a memory of the 2013 flood, when the Amur rose above 8 metres. He waited days for his owners on the porch of a flooded house; now, locals say, he "guards the whole city".`,
  '05 · финал': `05 · finale`,
  'Площадь Ленина и поющий фонтан': `Lenin Square and the singing fountain`,
  'Прогулка выводит к сердцу города: крупнейший в Евразии пешеходный светомузыкальный фонтан бьёт прямо из мостовой — почти 3 000 м² струй. Днём в нём носятся дети, вечером — водно-световое шоу под музыку.': `The walk leads to the city's heart: Eurasia's largest walk-through light-and-music fountain rises straight from the pavement — nearly 3,000 m² of jets. By day children dash through it; by night, a water-and-light show set to music.`,
  'Город': `City`,

  /* галерея — подписи */
  '01 · Речной вокзал': `01 · River terminal`,
  'Теплоходы уходят в Китай отсюда': `Riverboats to China leave from here`,
  '02 · Набережная Амура': `02 · The Amur embankment`,
  'Хэйхэ на том берегу': `Heihe on the far bank`,
  '03 · Собор Благовещения': `03 · Annunciation Cathedral`,
  'Семь золочёных куполов': `Seven gilded domes`,
  '04 · Мост через Амур': `04 · The bridge over the Amur`,
  'Первый автомост в Китай, стройка 2019-го': `The first road bridge to China, under construction in 2019`,
  '05 · Центр города': `05 · The city centre`,
  'Купеческий Благовещенск': `Merchant-era Blagoveshchensk`,
  '06 · Лотосы Комарова': `06 · Komarov lotuses`,
  'Цветут в июле у Ивановки': `Blooming in July near Ivanovka`,
  '07 · Космодром Восточный': `07 · Vostochny Cosmodrome`,
  'Первый пуск «Союза-2» · 180 км от города': `The first Soyuz-2 launch · 180 km from the city`,
  '08 · Муравьёв-Амурский': `08 · Muravyov-Amursky`,
  'Основатель города на набережной': `The city's founder on the embankment`,
  '09 · Площадь Ленина': `09 · Lenin Square`,
  'Пешеходный фонтан — крупнейший в Евразии': `A walk-through fountain — the largest in Eurasia`,

  /* футер — бренд */
  '<img class="logo" src="assets/logo-mark.png" alt="ИИщенко LAB" width="32" height="32">ИИщенко LAB': `<img class="logo" src="assets/logo-mark.png" alt="Iishchenko LAB" width="32" height="32">Iishchenko LAB`
};
